pkms = {'Bulbasaur': {'gender': 'GENDERLESS', 'forms': [0], 'id': 1},
        'Ivysaur': {'gender': 'GENDERLESS', 'forms': [0], 'id': 2},
        'Venusaur': {'gender': 'GENDERLESS', 'forms': [0], 'id': 3},
        'Charmander': {'gender': 'GENDERLESS', 'forms': [0], 'id': 4},
        'Charmeleon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 5},
        'Charizard': {'gender': 'GENDERLESS', 'forms': [0], 'id': 6},
        'Squirtle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 7},
        'Wartortle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 8},
        'Blastoise': {'gender': 'GENDERLESS', 'forms': [0], 'id': 9},
        'Caterpie': {'gender': 'GENDERLESS', 'forms': [0], 'id': 10},
        'Metapod': {'gender': 'GENDERLESS', 'forms': [0], 'id': 11},
        'Butterfree': {'gender': 'GENDERLESS', 'forms': [0], 'id': 12},
        'Weedle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 13},
        'Kakuna': {'gender': 'GENDERLESS', 'forms': [0], 'id': 14},
        'Beedrill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 15},
        'Pidgey': {'gender': 'GENDERLESS', 'forms': [0], 'id': 16},
        'Pidgeotto': {'gender': 'GENDERLESS', 'forms': [0], 'id': 17},
        'Pidgeot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 18},
        'Rattata': {'gender': 'GENDERLESS', 'forms': [0], 'id': 19},
        'Raticate': {'gender': 'GENDERLESS', 'forms': [0], 'id': 20},
        'Spearow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 21},
        'Fearow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 22},
        'Ekans': {'gender': 'GENDERLESS', 'forms': [0], 'id': 23},
        'Arbok': {'gender': 'GENDERLESS', 'forms': [0], 'id': 24},
        'Pikachu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 25},
        'Raichu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 26},
        'Sandshrew': {'gender': 'GENDERLESS', 'forms': [0], 'id': 27},
        'Sandslash': {'gender': 'GENDERLESS', 'forms': [0], 'id': 28},
        'Nidoran♀': {'gender': 'FEMALE', 'forms': [0], 'id': 29},
        'Nidorina': {'gender': 'FEMALE', 'forms': [0], 'id': 30},
        'Nidoqueen': {'gender': 'FEMALE', 'forms': [0], 'id': 31},
        'Nidoran♂': {'gender': 'MALE', 'forms': [0], 'id': 32},
        'Nidorino': {'gender': 'MALE', 'forms': [0], 'id': 33},
        'Nidoking': {'gender': 'MALE', 'forms': [0], 'id': 34},
        'Clefairy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 35},
        'Clefable': {'gender': 'GENDERLESS', 'forms': [0], 'id': 36},
        'Vulpix': {'gender': 'GENDERLESS', 'forms': [0], 'id': 37},
        'Ninetales': {'gender': 'GENDERLESS', 'forms': [0], 'id': 38},
        'Jigglypuff': {'gender': 'GENDERLESS', 'forms': [0], 'id': 39},
        'Wigglytuff': {'gender': 'GENDERLESS', 'forms': [0], 'id': 40},
        'Zubat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 41},
        'Golbat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 42},
        'Oddish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 43},
        'Gloom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 44},
        'Vileplume': {'gender': 'GENDERLESS', 'forms': [0], 'id': 45},
        'Paras': {'gender': 'GENDERLESS', 'forms': [0], 'id': 46},
        'Parasect': {'gender': 'GENDERLESS', 'forms': [0], 'id': 47},
        'Venonat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 48},
        'Venomoth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 49},
        'Diglett': {'gender': 'GENDERLESS', 'forms': [0], 'id': 50},
        'Dugtrio': {'gender': 'GENDERLESS', 'forms': [0], 'id': 51},
        'Meowth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 52},
        'Persian': {'gender': 'GENDERLESS', 'forms': [0], 'id': 53},
        'Psyduck': {'gender': 'GENDERLESS', 'forms': [0], 'id': 54},
        'Golduck': {'gender': 'GENDERLESS', 'forms': [0], 'id': 55},
        'Mankey': {'gender': 'GENDERLESS', 'forms': [0], 'id': 56},
        'Primeape': {'gender': 'GENDERLESS', 'forms': [0], 'id': 57},
        'Growlithe': {'gender': 'GENDERLESS', 'forms': [0], 'id': 58},
        'Arcanine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 59},
        'Poliwag': {'gender': 'GENDERLESS', 'forms': [0], 'id': 60},
        'Poliwhirl': {'gender': 'GENDERLESS', 'forms': [0], 'id': 61},
        'Poliwrath': {'gender': 'GENDERLESS', 'forms': [0], 'id': 62},
        'Abra': {'gender': 'GENDERLESS', 'forms': [0], 'id': 63},
        'Kadabra': {'gender': 'GENDERLESS', 'forms': [0], 'id': 64},
        'Alakazam': {'gender': 'GENDERLESS', 'forms': [0], 'id': 65},
        'Machop': {'gender': 'GENDERLESS', 'forms': [0], 'id': 66},
        'Machoke': {'gender': 'GENDERLESS', 'forms': [0], 'id': 67},
        'Machamp': {'gender': 'GENDERLESS', 'forms': [0], 'id': 68},
        'Bellsprout': {'gender': 'GENDERLESS', 'forms': [0], 'id': 69},
        'Weepinbell': {'gender': 'GENDERLESS', 'forms': [0], 'id': 70},
        'Victreebel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 71},
        'Tentacool': {'gender': 'GENDERLESS', 'forms': [0], 'id': 72},
        'Tentacruel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 73},
        'Geodude': {'gender': 'GENDERLESS', 'forms': [0], 'id': 74},
        'Graveler': {'gender': 'GENDERLESS', 'forms': [0], 'id': 75},
        'Golem': {'gender': 'GENDERLESS', 'forms': [0], 'id': 76},
        'Ponyta': {'gender': 'GENDERLESS', 'forms': [0], 'id': 77},
        'Rapidash': {'gender': 'GENDERLESS', 'forms': [0], 'id': 78},
        'Slowpoke': {'gender': 'GENDERLESS', 'forms': [0], 'id': 79},
        'Slowbro': {'gender': 'GENDERLESS', 'forms': [0], 'id': 80},
        'Magnemite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 81},
        'Magneton': {'gender': 'GENDERLESS', 'forms': [0], 'id': 82},
        "Farfetch'd": {'gender': 'GENDERLESS', 'forms': [0], 'id': 83},
        'Doduo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 84},
        'Dodrio': {'gender': 'GENDERLESS', 'forms': [0], 'id': 85},
        'Seel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 86},
        'Dewgong': {'gender': 'GENDERLESS', 'forms': [0], 'id': 87},
        'Grimer': {'gender': 'GENDERLESS', 'forms': [0], 'id': 88},
        'Muk': {'gender': 'GENDERLESS', 'forms': [0], 'id': 89},
        'Shellder': {'gender': 'GENDERLESS', 'forms': [0], 'id': 90},
        'Cloyster': {'gender': 'GENDERLESS', 'forms': [0], 'id': 91},
        'Gastly': {'gender': 'GENDERLESS', 'forms': [0], 'id': 92},
        'Haunter': {'gender': 'GENDERLESS', 'forms': [0], 'id': 93},
        'Gengar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 94},
        'Onix': {'gender': 'GENDERLESS', 'forms': [0], 'id': 95},
        'Drowzee': {'gender': 'GENDERLESS', 'forms': [0], 'id': 96},
        'Hypno': {'gender': 'GENDERLESS', 'forms': [0], 'id': 97},
        'Krabby': {'gender': 'GENDERLESS', 'forms': [0], 'id': 98},
        'Kingler': {'gender': 'GENDERLESS', 'forms': [0], 'id': 99},
        'Voltorb': {'gender': 'GENDERLESS', 'forms': [0], 'id': 100},
        'Electrode': {'gender': 'GENDERLESS', 'forms': [0], 'id': 101},
        'Exeggcute': {'gender': 'GENDERLESS', 'forms': [0], 'id': 102},
        'Exeggutor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 103},
        'Cubone': {'gender': 'GENDERLESS', 'forms': [0], 'id': 104},
        'Marowak': {'gender': 'GENDERLESS', 'forms': [0], 'id': 105},
        'Hitmonlee': {'gender': 'MALE', 'forms': [0], 'id': 106},
        'Hitmonchan': {'gender': 'MALE', 'forms': [0], 'id': 107},
        'Lickitung': {'gender': 'GENDERLESS', 'forms': [0], 'id': 108},
        'Koffing': {'gender': 'GENDERLESS', 'forms': [0], 'id': 109},
        'Weezing': {'gender': 'GENDERLESS', 'forms': [0], 'id': 110},
        'Rhyhorn': {'gender': 'GENDERLESS', 'forms': [0], 'id': 111},
        'Rhydon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 112},
        'Chansey': {'gender': 'FEMALE', 'forms': [0], 'id': 113},
        'Tangela': {'gender': 'GENDERLESS', 'forms': [0], 'id': 114},
        'Kangaskhan': {'gender': 'FEMALE', 'forms': [0], 'id': 115},
        'Horsea': {'gender': 'GENDERLESS', 'forms': [0], 'id': 116},
        'Seadra': {'gender': 'GENDERLESS', 'forms': [0], 'id': 117},
        'Goldeen': {'gender': 'GENDERLESS', 'forms': [0], 'id': 118},
        'Seaking': {'gender': 'GENDERLESS', 'forms': [0], 'id': 119},
        'Staryu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 120},
        'Starmie': {'gender': 'GENDERLESS', 'forms': [0], 'id': 121},
        'Mr. Mime': {'gender': 'GENDERLESS', 'forms': [0], 'id': 122},
        'Scyther': {'gender': 'GENDERLESS', 'forms': [0], 'id': 123},
        'Jynx': {'gender': 'FEMALE', 'forms': [0], 'id': 124},
        'Electabuzz': {'gender': 'GENDERLESS', 'forms': [0], 'id': 125},
        'Magmar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 126},
        'Pinsir': {'gender': 'GENDERLESS', 'forms': [0], 'id': 127},
        'Tauros': {'gender': 'MALE', 'forms': [0], 'id': 128},
        'Magikarp': {'gender': 'GENDERLESS', 'forms': [0], 'id': 129},
        'Gyarados': {'gender': 'GENDERLESS', 'forms': [0], 'id': 130},
        'Lapras': {'gender': 'GENDERLESS', 'forms': [0], 'id': 131},
        'Ditto': {'gender': 'GENDERLESS', 'forms': [0], 'id': 132},
        'Eevee': {'gender': 'GENDERLESS', 'forms': [0], 'id': 133},
        'Vaporeon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 134},
        'Jolteon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 135},
        'Flareon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 136},
        'Porygon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 137},
        'Omanyte': {'gender': 'GENDERLESS', 'forms': [0], 'id': 138},
        'Omastar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 139},
        'Kabuto': {'gender': 'GENDERLESS', 'forms': [0], 'id': 140},
        'Kabutops': {'gender': 'GENDERLESS', 'forms': [0], 'id': 141},
        'Aerodactyl': {'gender': 'GENDERLESS', 'forms': [0], 'id': 142},
        'Snorlax': {'gender': 'GENDERLESS', 'forms': [0], 'id': 143},
        'Articuno': {'gender': 'GENDERLESS', 'forms': [0], 'id': 144},
        'Zapdos': {'gender': 'GENDERLESS', 'forms': [0], 'id': 145},
        'Moltres': {'gender': 'GENDERLESS', 'forms': [0], 'id': 146},
        'Dratini': {'gender': 'GENDERLESS', 'forms': [0], 'id': 147},
        'Dragonair': {'gender': 'GENDERLESS', 'forms': [0], 'id': 148},
        'Dragonite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 149},
        'Mewtwo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 150},
        'Mew': {'gender': 'GENDERLESS', 'forms': [0], 'id': 151},
        'Chikorita': {'gender': 'GENDERLESS', 'forms': [0], 'id': 152},
        'Bayleef': {'gender': 'GENDERLESS', 'forms': [0], 'id': 153},
        'Meganium': {'gender': 'GENDERLESS', 'forms': [0], 'id': 154},
        'Cyndaquil': {'gender': 'GENDERLESS', 'forms': [0], 'id': 155},
        'Quilava': {'gender': 'GENDERLESS', 'forms': [0], 'id': 156},
        'Typhlosion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 157},
        'Totodile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 158},
        'Croconaw': {'gender': 'GENDERLESS', 'forms': [0], 'id': 159},
        'Feraligatr': {'gender': 'GENDERLESS', 'forms': [0], 'id': 160},
        'Sentret': {'gender': 'GENDERLESS', 'forms': [0], 'id': 161},
        'Furret': {'gender': 'GENDERLESS', 'forms': [0], 'id': 162},
        'Hoothoot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 163},
        'Noctowl': {'gender': 'GENDERLESS', 'forms': [0], 'id': 164},
        'Ledyba': {'gender': 'GENDERLESS', 'forms': [0], 'id': 165},
        'Ledian': {'gender': 'GENDERLESS', 'forms': [0], 'id': 166},
        'Spinarak': {'gender': 'GENDERLESS', 'forms': [0], 'id': 167},
        'Ariados': {'gender': 'GENDERLESS', 'forms': [0], 'id': 168},
        'Crobat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 169},
        'Chinchou': {'gender': 'GENDERLESS', 'forms': [0], 'id': 170},
        'Lanturn': {'gender': 'GENDERLESS', 'forms': [0], 'id': 171},
        'Pichu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 172},
        'Cleffa': {'gender': 'GENDERLESS', 'forms': [0], 'id': 173},
        'Igglybuff': {'gender': 'GENDERLESS', 'forms': [0], 'id': 174},
        'Togepi': {'gender': 'GENDERLESS', 'forms': [0], 'id': 175},
        'Togetic': {'gender': 'GENDERLESS', 'forms': [0], 'id': 176},
        'Natu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 177},
        'Xatu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 178},
        'Mareep': {'gender': 'GENDERLESS', 'forms': [0], 'id': 179},
        'Flaaffy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 180},
        'Ampharos': {'gender': 'GENDERLESS', 'forms': [0], 'id': 181},
        'Bellossom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 182},
        'Marill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 183},
        'Azumarill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 184},
        'Sudowoodo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 185},
        'Politoed': {'gender': 'GENDERLESS', 'forms': [0], 'id': 186},
        'Hoppip': {'gender': 'GENDERLESS', 'forms': [0], 'id': 187},
        'Skiploom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 188},
        'Jumpluff': {'gender': 'GENDERLESS', 'forms': [0], 'id': 189},
        'Aipom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 190},
        'Sunkern': {'gender': 'GENDERLESS', 'forms': [0], 'id': 191},
        'Sunflora': {'gender': 'GENDERLESS', 'forms': [0], 'id': 192},
        'Yanma': {'gender': 'GENDERLESS', 'forms': [0], 'id': 193},
        'Wooper': {'gender': 'GENDERLESS', 'forms': [0], 'id': 194},
        'Quagsire': {'gender': 'GENDERLESS', 'forms': [0], 'id': 195},
        'Espeon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 196},
        'Umbreon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 197},
        'Murkrow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 198},
        'Slowking': {'gender': 'GENDERLESS', 'forms': [0], 'id': 199},
        'Misdreavus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 200},
        'Unown': {'gender': 'GENDERLESS',
                  'forms': [0, 1, 2, 3, 4, 5, 6, 7, 8,
                            9, 10, 11, 12, 13, 14, 15,
                            16, 17, 18, 19, 20, 21, 22,
                            23, 24, 25, 26, 27],
                  'id': 201},
        'Wobbuffet': {'gender': 'GENDERLESS', 'forms': [0], 'id': 202},
        'Girafarig': {'gender': 'GENDERLESS', 'forms': [0], 'id': 203},
        'Pineco': {'gender': 'GENDERLESS', 'forms': [0], 'id': 204},
        'Forretress': {'gender': 'GENDERLESS', 'forms': [0], 'id': 205},
        'Dunsparce': {'gender': 'GENDERLESS', 'forms': [0], 'id': 206},
        'Gligar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 207},
        'Steelix': {'gender': 'GENDERLESS', 'forms': [0], 'id': 208},
        'Snubbull': {'gender': 'GENDERLESS', 'forms': [0], 'id': 209},
        'Granbull': {'gender': 'GENDERLESS', 'forms': [0], 'id': 210},
        'Qwilfish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 211},
        'Scizor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 212},
        'Shuckle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 213},
        'Heracross': {'gender': 'GENDERLESS', 'forms': [0], 'id': 214},
        'Sneasel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 215},
        'Teddiursa': {'gender': 'GENDERLESS', 'forms': [0], 'id': 216},
        'Ursaring': {'gender': 'GENDERLESS', 'forms': [0], 'id': 217},
        'Slugma': {'gender': 'GENDERLESS', 'forms': [0], 'id': 218},
        'Magcargo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 219},
        'Swinub': {'gender': 'GENDERLESS', 'forms': [0], 'id': 220},
        'Piloswine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 221},
        'Corsola': {'gender': 'GENDERLESS', 'forms': [0], 'id': 222},
        'Remoraid': {'gender': 'GENDERLESS', 'forms': [0], 'id': 223},
        'Octillery': {'gender': 'GENDERLESS', 'forms': [0], 'id': 224},
        'Delibird': {'gender': 'GENDERLESS', 'forms': [0], 'id': 225},
        'Mantine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 226},
        'Skarmory': {'gender': 'GENDERLESS', 'forms': [0], 'id': 227},
        'Houndour': {'gender': 'GENDERLESS', 'forms': [0], 'id': 228},
        'Houndoom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 229},
        'Kingdra': {'gender': 'GENDERLESS', 'forms': [0], 'id': 230},
        'Phanpy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 231},
        'Donphan': {'gender': 'GENDERLESS', 'forms': [0], 'id': 232},
        'Porygon2': {'gender': 'GENDERLESS', 'forms': [0], 'id': 233},
        'Stantler': {'gender': 'GENDERLESS', 'forms': [0], 'id': 234},
        'Smeargle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 235},
        'Tyrogue': {'gender': 'MALE', 'forms': [0], 'id': 236},
        'Hitmontop': {'gender': 'MALE', 'forms': [0], 'id': 237},
        'Smoochum': {'gender': 'GENDERLESS', 'forms': [0], 'id': 238},
        'Elekid': {'gender': 'GENDERLESS', 'forms': [0], 'id': 239},
        'Magby': {'gender': 'GENDERLESS', 'forms': [0], 'id': 240},
        'Miltank': {'gender': 'FEMALE', 'forms': [0], 'id': 241},
        'Blissey': {'gender': 'FEMALE', 'forms': [0], 'id': 242},
        'Raikou': {'gender': 'GENDERLESS', 'forms': [0], 'id': 243},
        'Entei': {'gender': 'GENDERLESS', 'forms': [0], 'id': 244},
        'Suicune': {'gender': 'GENDERLESS', 'forms': [0], 'id': 245},
        'Larvitar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 246},
        'Pupitar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 247},
        'Tyranitar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 248},
        'Lugia': {'gender': 'GENDERLESS', 'forms': [0], 'id': 249},
        'Ho-Oh': {'gender': 'GENDERLESS', 'forms': [0], 'id': 250},
        'Celebi': {'gender': 'GENDERLESS', 'forms': [0], 'id': 251},
        'Treecko': {'gender': 'GENDERLESS', 'forms': [0], 'id': 252},
        'Grovyle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 253},
        'Sceptile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 254},
        'Torchic': {'gender': 'GENDERLESS', 'forms': [0], 'id': 255},
        'Combusken': {'gender': 'GENDERLESS', 'forms': [0], 'id': 256},
        'Blaziken': {'gender': 'GENDERLESS', 'forms': [0], 'id': 257},
        'Mudkip': {'gender': 'GENDERLESS', 'forms': [0], 'id': 258},
        'Marshtomp': {'gender': 'GENDERLESS', 'forms': [0], 'id': 259},
        'Swampert': {'gender': 'GENDERLESS', 'forms': [0], 'id': 260},
        'Poochyena': {'gender': 'GENDERLESS', 'forms': [0], 'id': 261},
        'Mightyena': {'gender': 'GENDERLESS', 'forms': [0], 'id': 262},
        'Zigzagoon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 263},
        'Linoone': {'gender': 'GENDERLESS', 'forms': [0], 'id': 264},
        'Wurmple': {'gender': 'GENDERLESS', 'forms': [0], 'id': 265},
        'Silcoon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 266},
        'Beautifly': {'gender': 'GENDERLESS', 'forms': [0], 'id': 267},
        'Cascoon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 268},
        'Dustox': {'gender': 'GENDERLESS', 'forms': [0], 'id': 269},
        'Lotad': {'gender': 'GENDERLESS', 'forms': [0], 'id': 270},
        'Lombre': {'gender': 'GENDERLESS', 'forms': [0], 'id': 271},
        'Ludicolo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 272},
        'Seedot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 273},
        'Nuzleaf': {'gender': 'GENDERLESS', 'forms': [0], 'id': 274},
        'Shiftry': {'gender': 'GENDERLESS', 'forms': [0], 'id': 275},
        'Taillow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 276},
        'Swellow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 277},
        'Wingull': {'gender': 'GENDERLESS', 'forms': [0], 'id': 278},
        'Pelipper': {'gender': 'GENDERLESS', 'forms': [0], 'id': 279},
        'Ralts': {'gender': 'GENDERLESS', 'forms': [0], 'id': 280},
        'Kirlia': {'gender': 'GENDERLESS', 'forms': [0], 'id': 281},
        'Gardevoir': {'gender': 'GENDERLESS', 'forms': [0], 'id': 282},
        'Surskit': {'gender': 'GENDERLESS', 'forms': [0], 'id': 283},
        'Masquerain': {'gender': 'GENDERLESS', 'forms': [0], 'id': 284},
        'Shroomish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 285},
        'Breloom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 286},
        'Slakoth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 287},
        'Vigoroth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 288},
        'Slaking': {'gender': 'GENDERLESS', 'forms': [0], 'id': 289},
        'Nincada': {'gender': 'GENDERLESS', 'forms': [0], 'id': 290},
        'Ninjask': {'gender': 'GENDERLESS', 'forms': [0], 'id': 291},
        'Shedinja': {'gender': 'GENDERLESS', 'forms': [0], 'id': 292},
        'Whismur': {'gender': 'GENDERLESS', 'forms': [0], 'id': 293},
        'Loudred': {'gender': 'GENDERLESS', 'forms': [0], 'id': 294},
        'Exploud': {'gender': 'GENDERLESS', 'forms': [0], 'id': 295},
        'Makuhita': {'gender': 'GENDERLESS', 'forms': [0], 'id': 296},
        'Hariyama': {'gender': 'GENDERLESS', 'forms': [0], 'id': 297},
        'Azurill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 298},
        'Nosepass': {'gender': 'GENDERLESS', 'forms': [0], 'id': 299},
        'Skitty': {'gender': 'GENDERLESS', 'forms': [0], 'id': 300},
        'Delcatty': {'gender': 'GENDERLESS', 'forms': [0], 'id': 301},
        'Sableye': {'gender': 'GENDERLESS', 'forms': [0], 'id': 302},
        'Mawile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 303},
        'Aron': {'gender': 'GENDERLESS', 'forms': [0], 'id': 304},
        'Lairon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 305},
        'Aggron': {'gender': 'GENDERLESS', 'forms': [0], 'id': 306},
        'Meditite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 307},
        'Medicham': {'gender': 'GENDERLESS', 'forms': [0], 'id': 308},
        'Electrike': {'gender': 'GENDERLESS', 'forms': [0], 'id': 309},
        'Manectric': {'gender': 'GENDERLESS', 'forms': [0], 'id': 310},
        'Plusle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 311},
        'Minun': {'gender': 'GENDERLESS', 'forms': [0], 'id': 312},
        'Volbeat': {'gender': 'MALE', 'forms': [0], 'id': 313},
        'Illumise': {'gender': 'FEMALE', 'forms': [0], 'id': 314},
        'Roselia': {'gender': 'GENDERLESS', 'forms': [0], 'id': 315},
        'Gulpin': {'gender': 'GENDERLESS', 'forms': [0], 'id': 316},
        'Swalot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 317},
        'Carvanha': {'gender': 'GENDERLESS', 'forms': [0], 'id': 318},
        'Sharpedo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 319},
        'Wailmer': {'gender': 'GENDERLESS', 'forms': [0], 'id': 320},
        'Wailord': {'gender': 'GENDERLESS', 'forms': [0], 'id': 321},
        'Numel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 322},
        'Camerupt': {'gender': 'GENDERLESS', 'forms': [0], 'id': 323},
        'Torkoal': {'gender': 'GENDERLESS', 'forms': [0], 'id': 324},
        'Spoink': {'gender': 'GENDERLESS', 'forms': [0], 'id': 325},
        'Grumpig': {'gender': 'GENDERLESS', 'forms': [0], 'id': 326},
        'Spinda': {'gender': 'GENDERLESS', 'forms': [0], 'id': 327},
        'Trapinch': {'gender': 'GENDERLESS', 'forms': [0], 'id': 328},
        'Vibrava': {'gender': 'GENDERLESS', 'forms': [0], 'id': 329},
        'Flygon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 330},
        'Cacnea': {'gender': 'GENDERLESS', 'forms': [0], 'id': 331},
        'Cacturne': {'gender': 'GENDERLESS', 'forms': [0], 'id': 332},
        'Swablu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 333},
        'Altaria': {'gender': 'GENDERLESS', 'forms': [0], 'id': 334},
        'Zangoose': {'gender': 'GENDERLESS', 'forms': [0], 'id': 335},
        'Seviper': {'gender': 'GENDERLESS', 'forms': [0], 'id': 336},
        'Lunatone': {'gender': 'GENDERLESS', 'forms': [0], 'id': 337},
        'Solrock': {'gender': 'GENDERLESS', 'forms': [0], 'id': 338},
        'Barboach': {'gender': 'GENDERLESS', 'forms': [0], 'id': 339},
        'Whiscash': {'gender': 'GENDERLESS', 'forms': [0], 'id': 340},
        'Corphish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 341},
        'Crawdaunt': {'gender': 'GENDERLESS', 'forms': [0], 'id': 342},
        'Baltoy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 343},
        'Claydol': {'gender': 'GENDERLESS', 'forms': [0], 'id': 344},
        'Lileep': {'gender': 'GENDERLESS', 'forms': [0], 'id': 345},
        'Cradily': {'gender': 'GENDERLESS', 'forms': [0], 'id': 346},
        'Anorith': {'gender': 'GENDERLESS', 'forms': [0], 'id': 347},
        'Armaldo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 348},
        'Feebas': {'gender': 'GENDERLESS', 'forms': [0], 'id': 349},
        'Milotic': {'gender': 'GENDERLESS', 'forms': [0], 'id': 350},
        'Castform': {'gender': 'GENDERLESS', 'forms': [0], 'id': 351},
        'Kecleon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 352},
        'Shuppet': {'gender': 'GENDERLESS', 'forms': [0], 'id': 353},
        'Banette': {'gender': 'GENDERLESS', 'forms': [0], 'id': 354},
        'Duskull': {'gender': 'GENDERLESS', 'forms': [0], 'id': 355},
        'Dusclops': {'gender': 'GENDERLESS', 'forms': [0], 'id': 356},
        'Tropius': {'gender': 'GENDERLESS', 'forms': [0], 'id': 357},
        'Chimecho': {'gender': 'GENDERLESS', 'forms': [0], 'id': 358},
        'Absol': {'gender': 'GENDERLESS', 'forms': [0], 'id': 359},
        'Wynaut': {'gender': 'GENDERLESS', 'forms': [0], 'id': 360},
        'Snorunt': {'gender': 'GENDERLESS', 'forms': [0], 'id': 361},
        'Glalie': {'gender': 'GENDERLESS', 'forms': [0], 'id': 362},
        'Spheal': {'gender': 'GENDERLESS', 'forms': [0], 'id': 363},
        'Sealeo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 364},
        'Walrein': {'gender': 'GENDERLESS', 'forms': [0], 'id': 365},
        'Clamperl': {'gender': 'GENDERLESS', 'forms': [0], 'id': 366},
        'Huntail': {'gender': 'GENDERLESS', 'forms': [0], 'id': 367},
        'Gorebyss': {'gender': 'GENDERLESS', 'forms': [0], 'id': 368},
        'Relicanth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 369},
        'Luvdisc': {'gender': 'GENDERLESS', 'forms': [0], 'id': 370},
        'Bagon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 371},
        'Shelgon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 372},
        'Salamence': {'gender': 'GENDERLESS', 'forms': [0], 'id': 373},
        'Beldum': {'gender': 'GENDERLESS', 'forms': [0], 'id': 374},
        'Metang': {'gender': 'GENDERLESS', 'forms': [0], 'id': 375},
        'Metagross': {'gender': 'GENDERLESS', 'forms': [0], 'id': 376},
        'Regirock': {'gender': 'GENDERLESS', 'forms': [0], 'id': 377},
        'Regice': {'gender': 'GENDERLESS', 'forms': [0], 'id': 378},
        'Registeel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 379},
        'Latias': {'gender': 'FEMALE', 'forms': [0], 'id': 380},
        'Latios': {'gender': 'MALE', 'forms': [0], 'id': 381},
        'Kyogre': {'gender': 'GENDERLESS', 'forms': [0], 'id': 382},
        'Groudon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 383},
        'Rayquaza': {'gender': 'GENDERLESS', 'forms': [0], 'id': 384},
        'Jirachi': {'gender': 'GENDERLESS', 'forms': [0], 'id': 385},
        'Deoxys': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3], 'id': 386},
        'Turtwig': {'gender': 'GENDERLESS', 'forms': [0], 'id': 387},
        'Grotle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 388},
        'Torterra': {'gender': 'GENDERLESS', 'forms': [0], 'id': 389},
        'Chimchar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 390},
        'Monferno': {'gender': 'GENDERLESS', 'forms': [0], 'id': 391},
        'Infernape': {'gender': 'GENDERLESS', 'forms': [0], 'id': 392},
        'Piplup': {'gender': 'GENDERLESS', 'forms': [0], 'id': 393},
        'Prinplup': {'gender': 'GENDERLESS', 'forms': [0], 'id': 394},
        'Empoleon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 395},
        'Starly': {'gender': 'GENDERLESS', 'forms': [0], 'id': 396},
        'Staravia': {'gender': 'GENDERLESS', 'forms': [0], 'id': 397},
        'Staraptor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 398},
        'Bidoof': {'gender': 'GENDERLESS', 'forms': [0], 'id': 399},
        'Bibarel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 400},
        'Kricketot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 401},
        'Kricketune': {'gender': 'GENDERLESS', 'forms': [0], 'id': 402},
        'Shinx': {'gender': 'GENDERLESS', 'forms': [0], 'id': 403},
        'Luxio': {'gender': 'GENDERLESS', 'forms': [0], 'id': 404},
        'Luxray': {'gender': 'GENDERLESS', 'forms': [0], 'id': 405},
        'Budew': {'gender': 'GENDERLESS', 'forms': [0], 'id': 406},
        'Roserade': {'gender': 'GENDERLESS', 'forms': [0], 'id': 407},
        'Cranidos': {'gender': 'GENDERLESS', 'forms': [0], 'id': 408},
        'Rampardos': {'gender': 'GENDERLESS', 'forms': [0], 'id': 409},
        'Shieldon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 410},
        'Bastiodon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 411},
        'Burmy': {'gender': 'GENDERLESS', 'forms': [0, 1, 2], 'id': 412},
        'Wormadam': {'gender': 'FEMALE', 'forms': [0, 1, 2], 'id': 413},
        'Mothim': {'gender': 'MALE', 'forms': [0], 'id': 414},
        'Combee': {'gender': 'GENDERLESS', 'forms': [0], 'id': 415},
        'Vespiquen': {'gender': 'FEMALE', 'forms': [0], 'id': 416},
        'Pachirisu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 417},
        'Buizel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 418},
        'Floatzel': {'gender': 'GENDERLESS', 'forms': [0], 'id': 419},
        'Cherubi': {'gender': 'GENDERLESS', 'forms': [0], 'id': 420},
        'Cherrim': {'gender': 'GENDERLESS', 'forms': [0], 'id': 421},
        'Shellos': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 422},
        'Gastrodon': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 423},
        'Ambipom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 424},
        'Drifloon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 425},
        'Drifblim': {'gender': 'GENDERLESS', 'forms': [0], 'id': 426},
        'Buneary': {'gender': 'GENDERLESS', 'forms': [0], 'id': 427},
        'Lopunny': {'gender': 'GENDERLESS', 'forms': [0], 'id': 428},
        'Mismagius': {'gender': 'GENDERLESS', 'forms': [0], 'id': 429},
        'Honchkrow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 430},
        'Glameow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 431},
        'Purugly': {'gender': 'GENDERLESS', 'forms': [0], 'id': 432},
        'Chingling': {'gender': 'GENDERLESS', 'forms': [0], 'id': 433},
        'Stunky': {'gender': 'GENDERLESS', 'forms': [0], 'id': 434},
        'Skuntank': {'gender': 'GENDERLESS', 'forms': [0], 'id': 435},
        'Bronzor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 436},
        'Bronzong': {'gender': 'GENDERLESS', 'forms': [0], 'id': 437},
        'Bonsly': {'gender': 'GENDERLESS', 'forms': [0], 'id': 438},
        'Mime Jr.': {'gender': 'GENDERLESS', 'forms': [0], 'id': 439},
        'Happiny': {'gender': 'GENDERLESS', 'forms': [0], 'id': 440},
        'Chatot': {'gender': 'GENDERLESS', 'forms': [0], 'id': 441},
        'Spiritomb': {'gender': 'GENDERLESS', 'forms': [0], 'id': 442},
        'Gible': {'gender': 'GENDERLESS', 'forms': [0], 'id': 443},
        'Gabite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 444},
        'Garchomp': {'gender': 'GENDERLESS', 'forms': [0], 'id': 445},
        'Munchlax': {'gender': 'GENDERLESS', 'forms': [0], 'id': 446},
        'Riolu': {'gender': 'GENDERLESS', 'forms': [0], 'id': 447},
        'Lucario': {'gender': 'GENDERLESS', 'forms': [0], 'id': 448},
        'Hippopotas': {'gender': 'GENDERLESS', 'forms': [0], 'id': 449},
        'Hippowdon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 450},
        'Skorupi': {'gender': 'GENDERLESS', 'forms': [0], 'id': 451},
        'Drapion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 452},
        'Croagunk': {'gender': 'GENDERLESS', 'forms': [0], 'id': 453},
        'Toxicroak': {'gender': 'GENDERLESS', 'forms': [0], 'id': 454},
        'Carnivine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 455},
        'Finneon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 456},
        'Lumineon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 457},
        'Mantyke': {'gender': 'GENDERLESS', 'forms': [0], 'id': 458},
        'Snover': {'gender': 'GENDERLESS', 'forms': [0], 'id': 459},
        'Abomasnow': {'gender': 'GENDERLESS', 'forms': [0], 'id': 460},
        'Weavile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 461},
        'Magnezone': {'gender': 'GENDERLESS', 'forms': [0], 'id': 462},
        'Lickilicky': {'gender': 'GENDERLESS', 'forms': [0], 'id': 463},
        'Rhyperior': {'gender': 'GENDERLESS', 'forms': [0], 'id': 464},
        'Tangrowth': {'gender': 'GENDERLESS', 'forms': [0], 'id': 465},
        'Electivire': {'gender': 'GENDERLESS', 'forms': [0], 'id': 466},
        'Magmortar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 467},
        'Togekiss': {'gender': 'GENDERLESS', 'forms': [0], 'id': 468},
        'Yanmega': {'gender': 'GENDERLESS', 'forms': [0], 'id': 469},
        'Leafeon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 470},
        'Glaceon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 471},
        'Gliscor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 472},
        'Mamoswine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 473},
        'Porygon-Z': {'gender': 'GENDERLESS', 'forms': [0], 'id': 474},
        'Gallade': {'gender': 'MALE', 'forms': [0], 'id': 475},
        'Probopass': {'gender': 'GENDERLESS', 'forms': [0], 'id': 476},
        'Dusknoir': {'gender': 'GENDERLESS', 'forms': [0], 'id': 477},
        'Froslass': {'gender': 'FEMALE', 'forms': [0], 'id': 478},
        'Rotom': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3, 4, 5], 'id': 479},
        'Uxie': {'gender': 'GENDERLESS', 'forms': [0], 'id': 480},
        'Mesprit': {'gender': 'GENDERLESS', 'forms': [0], 'id': 481},
        'Azelf': {'gender': 'GENDERLESS', 'forms': [0], 'id': 482},
        'Dialga': {'gender': 'GENDERLESS', 'forms': [0], 'id': 483},
        'Palkia': {'gender': 'GENDERLESS', 'forms': [0], 'id': 484},
        'Heatran': {'gender': 'GENDERLESS', 'forms': [0], 'id': 485},
        'Regigigas': {'gender': 'GENDERLESS', 'forms': [0], 'id': 486},
        'Giratina': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 487},
        'Cresselia': {'gender': 'FEMALE', 'forms': [0], 'id': 488},
        'Phione': {'gender': 'GENDERLESS', 'forms': [0], 'id': 489},
        'Manaphy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 490},
        'Darkrai': {'gender': 'GENDERLESS', 'forms': [0], 'id': 491},
        'Shaymin': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 492},
        'Arceus': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                   'id': 493},
        'Victini': {'gender': 'GENDERLESS', 'forms': [0], 'id': 494},
        'Snivy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 495},
        'Servine': {'gender': 'GENDERLESS', 'forms': [0], 'id': 496},
        'Serperior': {'gender': 'GENDERLESS', 'forms': [0], 'id': 497},
        'Tepig': {'gender': 'GENDERLESS', 'forms': [0], 'id': 498},
        'Pignite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 499},
        'Emboar': {'gender': 'GENDERLESS', 'forms': [0], 'id': 500},
        'Oshawott': {'gender': 'GENDERLESS', 'forms': [0], 'id': 501},
        'Dewott': {'gender': 'GENDERLESS', 'forms': [0], 'id': 502},
        'Samurott': {'gender': 'GENDERLESS', 'forms': [0], 'id': 503},
        'Patrat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 504},
        'Watchog': {'gender': 'GENDERLESS', 'forms': [0], 'id': 505},
        'Lillipup': {'gender': 'GENDERLESS', 'forms': [0], 'id': 506},
        'Herdier': {'gender': 'GENDERLESS', 'forms': [0], 'id': 507},
        'Stoutland': {'gender': 'GENDERLESS', 'forms': [0], 'id': 508},
        'Purrloin': {'gender': 'GENDERLESS', 'forms': [0], 'id': 509},
        'Liepard': {'gender': 'GENDERLESS', 'forms': [0], 'id': 510},
        'Pansage': {'gender': 'GENDERLESS', 'forms': [0], 'id': 511},
        'Simisage': {'gender': 'GENDERLESS', 'forms': [0], 'id': 512},
        'Pansear': {'gender': 'GENDERLESS', 'forms': [0], 'id': 513},
        'Simisear': {'gender': 'GENDERLESS', 'forms': [0], 'id': 514},
        'Panpour': {'gender': 'GENDERLESS', 'forms': [0], 'id': 515},
        'Simipour': {'gender': 'GENDERLESS', 'forms': [0], 'id': 516},
        'Munna': {'gender': 'GENDERLESS', 'forms': [0], 'id': 517},
        'Musharna': {'gender': 'GENDERLESS', 'forms': [0], 'id': 518},
        'Pidove': {'gender': 'GENDERLESS', 'forms': [0], 'id': 519},
        'Tranquill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 520},
        'Unfezant': {'gender': 'GENDERLESS', 'forms': [0], 'id': 521},
        'Blitzle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 522},
        'Zebstrika': {'gender': 'GENDERLESS', 'forms': [0], 'id': 523},
        'Roggenrola': {'gender': 'GENDERLESS', 'forms': [0], 'id': 524},
        'Boldore': {'gender': 'GENDERLESS', 'forms': [0], 'id': 525},
        'Gigalith': {'gender': 'GENDERLESS', 'forms': [0], 'id': 526},
        'Woobat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 527},
        'Swoobat': {'gender': 'GENDERLESS', 'forms': [0], 'id': 528},
        'Drilbur': {'gender': 'GENDERLESS', 'forms': [0], 'id': 529},
        'Excadrill': {'gender': 'GENDERLESS', 'forms': [0], 'id': 530},
        'Audino': {'gender': 'GENDERLESS', 'forms': [0], 'id': 531},
        'Timburr': {'gender': 'GENDERLESS', 'forms': [0], 'id': 532},
        'Gurdurr': {'gender': 'GENDERLESS', 'forms': [0], 'id': 533},
        'Conkeldurr': {'gender': 'GENDERLESS', 'forms': [0], 'id': 534},
        'Tympole': {'gender': 'GENDERLESS', 'forms': [0], 'id': 535},
        'Palpitoad': {'gender': 'GENDERLESS', 'forms': [0], 'id': 536},
        'Seismitoad': {'gender': 'GENDERLESS', 'forms': [0], 'id': 537},
        'Throh': {'gender': 'MALE', 'forms': [0], 'id': 538},
        'Sawk': {'gender': 'MALE', 'forms': [0], 'id': 539},
        'Sewaddle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 540},
        'Swadloon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 541},
        'Leavanny': {'gender': 'GENDERLESS', 'forms': [0], 'id': 542},
        'Venipede': {'gender': 'GENDERLESS', 'forms': [0], 'id': 543},
        'Whirlipede': {'gender': 'GENDERLESS', 'forms': [0], 'id': 544},
        'Scolipede': {'gender': 'GENDERLESS', 'forms': [0], 'id': 545},
        'Cottonee': {'gender': 'GENDERLESS', 'forms': [0], 'id': 546},
        'Whimsicott': {'gender': 'GENDERLESS', 'forms': [0], 'id': 547},
        'Petilil': {'gender': 'FEMALE', 'forms': [0], 'id': 548},
        'Lilligant': {'gender': 'FEMALE', 'forms': [0], 'id': 549},
        'Basculin': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 550},
        'Sandile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 551},
        'Krokorok': {'gender': 'GENDERLESS', 'forms': [0], 'id': 552},
        'Krookodile': {'gender': 'GENDERLESS', 'forms': [0], 'id': 553},
        'Darumaka': {'gender': 'GENDERLESS', 'forms': [0], 'id': 554},
        'Darmanitan': {'gender': 'GENDERLESS', 'forms': [0], 'id': 555},
        'Maractus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 556},
        'Dwebble': {'gender': 'GENDERLESS', 'forms': [0], 'id': 557},
        'Crustle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 558},
        'Scraggy': {'gender': 'GENDERLESS', 'forms': [0], 'id': 559},
        'Scrafty': {'gender': 'GENDERLESS', 'forms': [0], 'id': 560},
        'Sigilyph': {'gender': 'GENDERLESS', 'forms': [0], 'id': 561},
        'Yamask': {'gender': 'GENDERLESS', 'forms': [0], 'id': 562},
        'Cofagrigus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 563},
        'Tirtouga': {'gender': 'GENDERLESS', 'forms': [0], 'id': 564},
        'Carracosta': {'gender': 'GENDERLESS', 'forms': [0], 'id': 565},
        'Archen': {'gender': 'GENDERLESS', 'forms': [0], 'id': 566},
        'Archeops': {'gender': 'GENDERLESS', 'forms': [0], 'id': 567},
        'Trubbish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 568},
        'Garbodor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 569},
        'Zorua': {'gender': 'GENDERLESS', 'forms': [0], 'id': 570},
        'Zoroark': {'gender': 'GENDERLESS', 'forms': [0], 'id': 571},
        'Minccino': {'gender': 'GENDERLESS', 'forms': [0], 'id': 572},
        'Cinccino': {'gender': 'GENDERLESS', 'forms': [0], 'id': 573},
        'Gothita': {'gender': 'GENDERLESS', 'forms': [0], 'id': 574},
        'Gothorita': {'gender': 'GENDERLESS', 'forms': [0], 'id': 575},
        'Gothitelle': {'gender': 'GENDERLESS', 'forms': [0], 'id': 576},
        'Solosis': {'gender': 'GENDERLESS', 'forms': [0], 'id': 577},
        'Duosion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 578},
        'Reuniclus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 579},
        'Ducklett': {'gender': 'GENDERLESS', 'forms': [0], 'id': 580},
        'Swanna': {'gender': 'GENDERLESS', 'forms': [0], 'id': 581},
        'Vanillite': {'gender': 'GENDERLESS', 'forms': [0], 'id': 582},
        'Vanillish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 583},
        'Vanilluxe': {'gender': 'GENDERLESS', 'forms': [0], 'id': 584},
        'Deerling': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3], 'id': 585},
        'Sawsbuck': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3], 'id': 586},
        'Emolga': {'gender': 'GENDERLESS', 'forms': [0], 'id': 587},
        'Karrablast': {'gender': 'GENDERLESS', 'forms': [0], 'id': 588},
        'Escavalier': {'gender': 'GENDERLESS', 'forms': [0], 'id': 589},
        'Foongus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 590},
        'Amoonguss': {'gender': 'GENDERLESS', 'forms': [0], 'id': 591},
        'Frillish': {'gender': 'GENDERLESS', 'forms': [0], 'id': 592},
        'Jellicent': {'gender': 'GENDERLESS', 'forms': [0], 'id': 593},
        'Alomomola': {'gender': 'GENDERLESS', 'forms': [0], 'id': 594},
        'Joltik': {'gender': 'GENDERLESS', 'forms': [0], 'id': 595},
        'Galvantula': {'gender': 'GENDERLESS', 'forms': [0], 'id': 596},
        'Ferroseed': {'gender': 'GENDERLESS', 'forms': [0], 'id': 597},
        'Ferrothorn': {'gender': 'GENDERLESS', 'forms': [0], 'id': 598},
        'Klink': {'gender': 'GENDERLESS', 'forms': [0], 'id': 599},
        'Klang': {'gender': 'GENDERLESS', 'forms': [0], 'id': 600},
        'Klinklang': {'gender': 'GENDERLESS', 'forms': [0], 'id': 601},
        'Tynamo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 602},
        'Eelektrik': {'gender': 'GENDERLESS', 'forms': [0], 'id': 603},
        'Eelektross': {'gender': 'GENDERLESS', 'forms': [0], 'id': 604},
        'Elgyem': {'gender': 'GENDERLESS', 'forms': [0], 'id': 605},
        'Beheeyem': {'gender': 'GENDERLESS', 'forms': [0], 'id': 606},
        'Litwick': {'gender': 'GENDERLESS', 'forms': [0], 'id': 607},
        'Lampent': {'gender': 'GENDERLESS', 'forms': [0], 'id': 608},
        'Chandelure': {'gender': 'GENDERLESS', 'forms': [0], 'id': 609},
        'Axew': {'gender': 'GENDERLESS', 'forms': [0], 'id': 610},
        'Fraxure': {'gender': 'GENDERLESS', 'forms': [0], 'id': 611},
        'Haxorus': {'gender': 'GENDERLESS', 'forms': [0], 'id': 612},
        'Cubchoo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 613},
        'Beartic': {'gender': 'GENDERLESS', 'forms': [0], 'id': 614},
        'Cryogonal': {'gender': 'GENDERLESS', 'forms': [0], 'id': 615},
        'Shelmet': {'gender': 'GENDERLESS', 'forms': [0], 'id': 616},
        'Accelgor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 617},
        'Stunfisk': {'gender': 'GENDERLESS', 'forms': [0], 'id': 618},
        'Mienfoo': {'gender': 'GENDERLESS', 'forms': [0], 'id': 619},
        'Mienshao': {'gender': 'GENDERLESS', 'forms': [0], 'id': 620},
        'Druddigon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 621},
        'Golett': {'gender': 'GENDERLESS', 'forms': [0], 'id': 622},
        'Golurk': {'gender': 'GENDERLESS', 'forms': [0], 'id': 623},
        'Pawniard': {'gender': 'GENDERLESS', 'forms': [0], 'id': 624},
        'Bisharp': {'gender': 'GENDERLESS', 'forms': [0], 'id': 625},
        'Bouffalant': {'gender': 'GENDERLESS', 'forms': [0], 'id': 626},
        'Rufflet': {'gender': 'MALE', 'forms': [0], 'id': 627},
        'Braviary': {'gender': 'MALE', 'forms': [0], 'id': 628},
        'Vullaby': {'gender': 'FEMALE', 'forms': [0], 'id': 629},
        'Mandibuzz': {'gender': 'FEMALE', 'forms': [0], 'id': 630},
        'Heatmor': {'gender': 'GENDERLESS', 'forms': [0], 'id': 631},
        'Durant': {'gender': 'GENDERLESS', 'forms': [0], 'id': 632},
        'Deino': {'gender': 'GENDERLESS', 'forms': [0], 'id': 633},
        'Zweilous': {'gender': 'GENDERLESS', 'forms': [0], 'id': 634},
        'Hydreigon': {'gender': 'GENDERLESS', 'forms': [0], 'id': 635},
        'Larvesta': {'gender': 'GENDERLESS', 'forms': [0], 'id': 636},
        'Volcarona': {'gender': 'GENDERLESS', 'forms': [0], 'id': 637},
        'Cobalion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 638},
        'Terrakion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 639},
        'Virizion': {'gender': 'GENDERLESS', 'forms': [0], 'id': 640},
        'Tornadus': {'gender': 'MALE', 'forms': [0, 1], 'id': 641},
        'Thundurus': {'gender': 'MALE', 'forms': [0, 1], 'id': 642},
        'Reshiram': {'gender': 'GENDERLESS', 'forms': [0], 'id': 643},
        'Zekrom': {'gender': 'GENDERLESS', 'forms': [0], 'id': 644},
        'Landorus': {'gender': 'MALE', 'forms': [0, 1], 'id': 645},
        'Kyurem': {'gender': 'GENDERLESS', 'forms': [0, 1, 2], 'id': 646},
        'Keldeo': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 647},
        'Meloetta': {'gender': 'GENDERLESS', 'forms': [0, 1], 'id': 648},
        'Genesect': {'gender': 'GENDERLESS', 'forms': [0, 1, 2, 3, 4], 'id': 649}}
moves = {'Pound': 1, 'Karate Chop': 2, 'Double Slap': 3, 'Comet Punch': 4, 'Mega Punch': 5, 'Pay Day': 6,
         'Fire Punch': 7, 'Ice Punch': 8, 'Thunder Punch': 9, 'Scratch': 10, 'Vice Grip': 11, 'Guillotine': 12,
         'Razor Wind': 13, 'Swords Dance': 14, 'Cut': 15, 'Gust': 16, 'Wing Attack': 17, 'Whirlwind': 18, 'Fly': 19,
         'Bind': 20, 'Slam': 21, 'Vine Whip': 22, 'Stomp': 23, 'Double Kick': 24, 'Mega Kick': 25, 'Jump Kick': 26,
         'Rolling Kick': 27, 'Sand Attack': 28, 'Headbutt': 29, 'Horn Attack': 30, 'Fury Attack': 31, 'Horn Drill': 32,
         'Tackle': 33, 'Body Slam': 34, 'Wrap': 35, 'Take Down': 36, 'Thrash': 37, 'Double-Edge': 38, 'Tail Whip': 39,
         'Poison Sting': 40, 'Twineedle': 41, 'Pin Missile': 42, 'Leer': 43, 'Bite': 44, 'Growl': 45, 'Roar': 46,
         'Sing': 47, 'Supersonic': 48, 'Sonic Boom': 49, 'Disable': 50, 'Acid': 51, 'Ember': 52, 'Flamethrower': 53,
         'Mist': 54, 'Water Gun': 55, 'Hydro Pump': 56, 'Surf': 57, 'Ice Beam': 58, 'Blizzard': 59, 'Psybeam': 60,
         'Bubble Beam': 61, 'Aurora Beam': 62, 'Hyper Beam': 63, 'Peck': 64, 'Drill Peck': 65, 'Submission': 66,
         'Low Kick': 67, 'Counter': 68, 'Seismic Toss': 69, 'Strength': 70, 'Absorb': 71, 'Mega Drain': 72,
         'Leech Seed': 73, 'Growth': 74, 'Razor Leaf': 75, 'Solar Beam': 76, 'Poison Powder': 77, 'Stun Spore': 78,
         'Sleep Powder': 79, 'Petal Dance': 80, 'String Shot': 81, 'Dragon Rage': 82, 'Fire Spin': 83,
         'Thunder Shock': 84, 'Thunderbolt': 85, 'Thunder Wave': 86, 'Thunder': 87, 'Rock Throw': 88, 'Earthquake': 89,
         'Fissure': 90, 'Dig': 91, 'Toxic': 92, 'Confusion': 93, 'Psychic': 94, 'Hypnosis': 95, 'Meditate': 96,
         'Agility': 97, 'Quick Attack': 98, 'Rage': 99, 'Teleport': 100, 'Night Shade': 101, 'Mimic': 102,
         'Screech': 103, 'Double Team': 104, 'Recover': 105, 'Harden': 106, 'Minimize': 107, 'Smokescreen': 108,
         'Confuse Ray': 109, 'Withdraw': 110, 'Defense Curl': 111, 'Barrier': 112, 'Light Screen': 113, 'Haze': 114,
         'Reflect': 115, 'Focus Energy': 116, 'Bide': 117, 'Metronome': 118, 'Mirror Move': 119, 'Self-Destruct': 120,
         'Egg Bomb': 121, 'Lick': 122, 'Smog': 123, 'Sludge': 124, 'Bone Club': 125, 'Fire Blast': 126,
         'Waterfall': 127, 'Clamp': 128, 'Swift': 129, 'Skull Bash': 130, 'Spike Cannon': 131, 'Constrict': 132,
         'Amnesia': 133, 'Kinesis': 134, 'Soft-Boiled': 135, 'High Jump Kick': 136, 'Glare': 137, 'Dream Eater': 138,
         'Poison Gas': 139, 'Barrage': 140, 'Leech Life': 141, 'Lovely Kiss': 142, 'Sky Attack': 143, 'Transform': 144,
         'Bubble': 145, 'Dizzy Punch': 146, 'Spore': 147, 'Flash': 148, 'Psywave': 149, 'Splash': 150,
         'Acid Armor': 151, 'Crabhammer': 152, 'Explosion': 153, 'Fury Swipes': 154, 'Bonemerang': 155, 'Rest': 156,
         'Rock Slide': 157, 'Hyper Fang': 158, 'Sharpen': 159, 'Conversion': 160, 'Tri Attack': 161, 'Super Fang': 162,
         'Slash': 163, 'Substitute': 164, 'Struggle': 165, 'Sketch': 166, 'Triple Kick': 167, 'Thief': 168,
         'Spider Web': 169, 'Mind Reader': 170, 'Nightmare': 171, 'Flame Wheel': 172, 'Snore': 173, 'Curse': 174,
         'Flail': 175, 'Conversion 2': 176, 'Aeroblast': 177, 'Cotton Spore': 178, 'Reversal': 179, 'Spite': 180,
         'Powder Snow': 181, 'Protect': 182, 'Mach Punch': 183, 'Scary Face': 184, 'Faint Attack': 185,
         'Sweet Kiss': 186, 'Belly Drum': 187, 'Sludge Bomb': 188, 'Mud-Slap': 189, 'Octazooka': 190, 'Spikes': 191,
         'Zap Cannon': 192, 'Foresight': 193, 'Destiny Bond': 194, 'Perish Song': 195, 'Icy Wind': 196, 'Detect': 197,
         'Bone Rush': 198, 'Lock-On': 199, 'Outrage': 200, 'Sandstorm': 201, 'Giga Drain': 202, 'Endure': 203,
         'Charm': 204, 'Rollout': 205, 'False Swipe': 206, 'Swagger': 207, 'Milk Drink': 208, 'Spark': 209,
         'Fury Cutter': 210, 'Steel Wing': 211, 'Mean Look': 212, 'Attract': 213, 'Sleep Talk': 214, 'Heal Bell': 215,
         'Return': 216, 'Present': 217, 'Frustration': 218, 'Safeguard': 219, 'Pain Split': 220, 'Sacred Fire': 221,
         'Magnitude': 222, 'Dynamic Punch': 223, 'Megahorn': 224, 'Dragon Breath': 225, 'Baton Pass': 226,
         'Encore': 227, 'Pursuit': 228, 'Rapid Spin': 229, 'Sweet Scent': 230, 'Iron Tail': 231, 'Metal Claw': 232,
         'Vital Throw': 233, 'Morning Sun': 234, 'Synthesis': 235, 'Moonlight': 236, 'Hidden Power': 237,
         'Cross Chop': 238, 'Twister': 239, 'Rain Dance': 240, 'Sunny Day': 241, 'Crunch': 242, 'Mirror Coat': 243,
         'Psych Up': 244, 'Extreme Speed': 245, 'Ancient Power': 246, 'Shadow Ball': 247, 'Future Sight': 248,
         'Rock Smash': 249, 'Whirlpool': 250, 'Beat Up': 251, 'Fake Out': 252, 'Uproar': 253, 'Stockpile': 254,
         'Spit Up': 255, 'Swallow': 256, 'Heat Wave': 257, 'Hail': 258, 'Torment': 259, 'Flatter': 260,
         'Will-O-Wisp': 261, 'Memento': 262, 'Facade': 263, 'Focus Punch': 264, 'Smelling Salts': 265, 'Follow Me': 266,
         'Nature Power': 267, 'Charge': 268, 'Taunt': 269, 'Helping Hand': 270, 'Trick': 271, 'Role Play': 272,
         'Wish': 273, 'Assist': 274, 'Ingrain': 275, 'Superpower': 276, 'Magic Coat': 277, 'Recycle': 278,
         'Revenge': 279, 'Brick Break': 280, 'Yawn': 281, 'Knock Off': 282, 'Endeavor': 283, 'Eruption': 284,
         'Skill Swap': 285, 'Imprison': 286, 'Refresh': 287, 'Grudge': 288, 'Snatch': 289, 'Secret Power': 290,
         'Dive': 291, 'Arm Thrust': 292, 'Camouflage': 293, 'Tail Glow': 294, 'Luster Purge': 295, 'Mist Ball': 296,
         'Feather Dance': 297, 'Teeter Dance': 298, 'Blaze Kick': 299, 'Mud Sport': 300, 'Ice Ball': 301,
         'Needle Arm': 302, 'Slack Off': 303, 'Hyper Voice': 304, 'Poison Fang': 305, 'Crush Claw': 306,
         'Blast Burn': 307, 'Hydro Cannon': 308, 'Meteor Mash': 309, 'Astonish': 310, 'Weather Ball': 311,
         'Aromatherapy': 312, 'Fake Tears': 313, 'Air Cutter': 314, 'Overheat': 315, 'Odor Sleuth': 316,
         'Rock Tomb': 317, 'Silver Wind': 318, 'Metal Sound': 319, 'Grass Whistle': 320, 'Tickle': 321,
         'Cosmic Power': 322, 'Water Spout': 323, 'Signal Beam': 324, 'Shadow Punch': 325, 'Extrasensory': 326,
         'Sky Uppercut': 327, 'Sand Tomb': 328, 'Sheer Cold': 329, 'Muddy Water': 330, 'Bullet Seed': 331,
         'Aerial Ace': 332, 'Icicle Spear': 333, 'Iron Defense': 334, 'Block': 335, 'Howl': 336, 'Dragon Claw': 337,
         'Frenzy Plant': 338, 'Bulk Up': 339, 'Bounce': 340, 'Mud Shot': 341, 'Poison Tail': 342, 'Covet': 343,
         'Volt Tackle': 344, 'Magical Leaf': 345, 'Water Sport': 346, 'Calm Mind': 347, 'Leaf Blade': 348,
         'Dragon Dance': 349, 'Rock Blast': 350, 'Shock Wave': 351, 'Water Pulse': 352, 'Doom Desire': 353,
         'Psycho Boost': 354, 'Roost': 355, 'Gravity': 356, 'Miracle Eye': 357, 'Wake-Up Slap': 358, 'Hammer Arm': 359,
         'Gyro Ball': 360, 'Healing Wish': 361, 'Brine': 362, 'Natural Gift': 363, 'Feint': 364, 'Pluck': 365,
         'Tailwind': 366, 'Acupressure': 367, 'Metal Burst': 368, 'U-turn': 369, 'Close Combat': 370, 'Payback': 371,
         'Assurance': 372, 'Embargo': 373, 'Fling': 374, 'Psycho Shift': 375, 'Trump Card': 376, 'Heal Block': 377,
         'Wring Out': 378, 'Power Trick': 379, 'Gastro Acid': 380, 'Lucky Chant': 381, 'Me First': 382, 'Copycat': 383,
         'Power Swap': 384, 'Guard Swap': 385, 'Punishment': 386, 'Last Resort': 387, 'Worry Seed': 388,
         'Sucker Punch': 389, 'Toxic Spikes': 390, 'Heart Swap': 391, 'Aqua Ring': 392, 'Magnet Rise': 393,
         'Flare Blitz': 394, 'Force Palm': 395, 'Aura Sphere': 396, 'Rock Polish': 397, 'Poison Jab': 398,
         'Dark Pulse': 399, 'Night Slash': 400, 'Aqua Tail': 401, 'Seed Bomb': 402, 'Air Slash': 403, 'X-Scissor': 404,
         'Bug Buzz': 405, 'Dragon Pulse': 406, 'Dragon Rush': 407, 'Power Gem': 408, 'Drain Punch': 409,
         'Vacuum Wave': 410, 'Focus Blast': 411, 'Energy Ball': 412, 'Brave Bird': 413, 'Earth Power': 414,
         'Switcheroo': 415, 'Giga Impact': 416, 'Nasty Plot': 417, 'Bullet Punch': 418, 'Avalanche': 419,
         'Ice Shard': 420, 'Shadow Claw': 421, 'Thunder Fang': 422, 'Ice Fang': 423, 'Fire Fang': 424,
         'Shadow Sneak': 425, 'Mud Bomb': 426, 'Psycho Cut': 427, 'Zen Headbutt': 428, 'Mirror Shot': 429,
         'Flash Cannon': 430, 'Rock Climb': 431, 'Defog': 432, 'Trick Room': 433, 'Draco Meteor': 434, 'Discharge': 435,
         'Lava Plume': 436, 'Leaf Storm': 437, 'Power Whip': 438, 'Rock Wrecker': 439, 'Cross Poison': 440,
         'Gunk Shot': 441, 'Iron Head': 442, 'Magnet Bomb': 443, 'Stone Edge': 444, 'Captivate': 445,
         'Stealth Rock': 446, 'Grass Knot': 447, 'Chatter': 448, 'Judgment': 449, 'Bug Bite': 450, 'Charge Beam': 451,
         'Wood Hammer': 452, 'Aqua Jet': 453, 'Attack Order': 454, 'Defend Order': 455, 'Heal Order': 456,
         'Head Smash': 457, 'Double Hit': 458, 'Roar of Time': 459, 'Spacial Rend': 460, 'Lunar Dance': 461,
         'Crush Grip': 462, 'Magma Storm': 463, 'Dark Void': 464, 'Seed Flare': 465, 'Ominous Wind': 466,
         'Shadow Force': 467, 'Hone Claws': 468, 'Wide Guard': 469, 'Guard Split': 470, 'Power Split': 471,
         'Wonder Room': 472, 'Psyshock': 473, 'Venoshock': 474, 'Autotomize': 475, 'Rage Powder': 476,
         'Telekinesis': 477, 'Magic Room': 478, 'Smack Down': 479, 'Storm Throw': 480, 'Flame Burst': 481,
         'Sludge Wave': 482, 'Quiver Dance': 483, 'Heavy Slam': 484, 'Synchronoise': 485, 'Electro Ball': 486,
         'Soak': 487, 'Flame Charge': 488, 'Coil': 489, 'Low Sweep': 490, 'Acid Spray': 491, 'Foul Play': 492,
         'Simple Beam': 493, 'Entrainment': 494, 'After You': 495, 'Round': 496, 'Echoed Voice': 497, 'Chip Away': 498,
         'Clear Smog': 499, 'Stored Power': 500, 'Quick Guard': 501, 'Ally Switch': 502, 'Scald': 503,
         'Shell Smash': 504, 'Heal Pulse': 505, 'Hex': 506, 'Sky Drop': 507, 'Shift Gear': 508, 'Circle Throw': 509,
         'Incinerate': 510, 'Quash': 511, 'Acrobatics': 512, 'Reflect Type': 513, 'Retaliate': 514, 'Final Gambit': 515,
         'Bestow': 516, 'Inferno': 517, 'Water Pledge': 518, 'Fire Pledge': 519, 'Grass Pledge': 520,
         'Volt Switch': 521, 'Struggle Bug': 522, 'Bulldoze': 523, 'Frost Breath': 524, 'Dragon Tail': 525,
         'Work Up': 526, 'Electroweb': 527, 'Wild Charge': 528, 'Drill Run': 529, 'Dual Chop': 530, 'Heart Stamp': 531,
         'Horn Leech': 532, 'Sacred Sword': 533, 'Razor Shell': 534, 'Heat Crash': 535, 'Leaf Tornado': 536,
         'Steamroller': 537, 'Cotton Guard': 538, 'Night Daze': 539, 'Psystrike': 540, 'Tail Slap': 541,
         'Hurricane': 542, 'Head Charge': 543, 'Gear Grind': 544, 'Searing Shot': 545, 'Techno Blast': 546,
         'Relic Song': 547, 'Secret Sword': 548, 'Glaciate': 549, 'Bolt Strike': 550, 'Blue Flare': 551,
         'Fiery Dance': 552, 'Freeze Shock': 553, 'Ice Burn': 554, 'Snarl': 555, 'Icicle Crash': 556, 'V-create': 557,
         'Fusion Flare': 558, 'Fusion Bolt': 559}
items = {'Master Ball': 1, 'Ultra Ball': 2, 'Great Ball': 3, 'Poké Ball': 4, 'Safari Ball': 5, 'Net Ball': 6,
         'Dive Ball': 7, 'Nest Ball': 8, 'Repeat Ball': 9, 'Timer Ball': 10, 'Luxury Ball': 11, 'Premier Ball': 12,
         'Dusk Ball': 13, 'Heal Ball': 14, 'Quick Ball': 15, 'Cherish Ball': 16, 'Potion': 17, 'Antidote': 18,
         'Burn Heal': 19, 'Ice Heal': 20, 'Awakening': 21, 'Paralyze Heal': 22, 'Full Restore': 23, 'Max Potion': 24,
         'Hyper Potion': 25, 'Super Potion': 26, 'Full Heal': 27, 'Revive': 28, 'Max Revive': 29, 'Fresh Water': 30,
         'Soda Pop': 31, 'Lemonade': 32, 'Moomoo Milk': 33, 'Energy Powder': 34, 'Energy Root': 35, 'Heal Powder': 36,
         'Revival Herb': 37, 'Ether': 38, 'Max Ether': 39, 'Elixir': 40, 'Max Elixir': 41, 'Lava Cookie': 42,
         'Berry Juice': 43, 'Sacred Ash': 44, 'HP Up': 45, 'Protein': 46, 'Iron': 47, 'Carbos': 48, 'Calcium': 49,
         'Rare Candy': 50, 'PP Up': 51, 'Zinc': 52, 'PP Max': 53, 'Old Gateau': 54, 'Guard Spec.': 55, 'Dire Hit': 56,
         'X Attack': 57, 'X Defense': 58, 'X Speed': 59, 'X Accuracy': 60, 'X Sp. Atk': 61, 'X Sp. Def': 62,
         'Poké Doll': 63, 'Fluffy Tail': 64, 'Blue Flute': 65, 'Yellow Flute': 66, 'Red Flute': 67, 'Black Flute': 68,
         'White Flute': 69, 'Shoal Salt': 70, 'Shoal Shell': 71, 'Red Shard': 72, 'Blue Shard': 73, 'Yellow Shard': 74,
         'Green Shard': 75, 'Super Repel': 76, 'Max Repel': 77, 'Escape Rope': 78, 'Repel': 79, 'Sun Stone': 80,
         'Moon Stone': 81, 'Fire Stone': 82, 'Thunder Stone': 83, 'Water Stone': 84, 'Leaf Stone': 85,
         'Tiny Mushroom': 86, 'Big Mushroom': 87, 'Pearl': 88, 'Big Pearl': 89, 'Stardust': 90, 'Star Piece': 91,
         'Nugget': 92, 'Heart Scale': 93, 'Honey': 94, 'Growth Mulch': 95, 'Damp Mulch': 96, 'Stable Mulch': 97,
         'Gooey Mulch': 98, 'Root Fossil': 99, 'Claw Fossil': 100, 'Helix Fossil': 101, 'Dome Fossil': 102,
         'Old Amber': 103, 'Armor Fossil': 104, 'Skull Fossil': 105, 'Rare Bone': 106, 'Shiny Stone': 107,
         'Dusk Stone': 108, 'Dawn Stone': 109, 'Oval Stone': 110, 'Odd Keystone': 111, 'Griseous Orb': 112,
         'Douse Drive': 116, 'Shock Drive': 117, 'Burn Drive': 118, 'Chill Drive': 119, 'Sweet Heart': 134,
         'Adamant Orb': 135, 'Lustrous Orb': 136, 'Greet Mail': 137, 'Favored Mail': 138, 'RSVP Mail': 139,
         'Thanks Mail': 140, 'Inquiry Mail': 141, 'Like Mail': 142, 'Reply Mail': 143, 'Bridge Mail S': 144,
         'Bridge Mail D': 145, 'Bridge Mail T': 146, 'Bridge Mail V': 147, 'Bridge Mail M': 148, 'Cheri Berry': 149,
         'Chesto Berry': 150, 'Pecha Berry': 151, 'Rawst Berry': 152, 'Aspear Berry': 153, 'Leppa Berry': 154,
         'Oran Berry': 155, 'Persim Berry': 156, 'Lum Berry': 157, 'Sitrus Berry': 158, 'Figy Berry': 159,
         'Wiki Berry': 160, 'Mago Berry': 161, 'Aguav Berry': 162, 'Iapapa Berry': 163, 'Razz Berry': 164,
         'Bluk Berry': 165, 'Nanab Berry': 166, 'Wepear Berry': 167, 'Pinap Berry': 168, 'Pomeg Berry': 169,
         'Kelpsy Berry': 170, 'Qualot Berry': 171, 'Hondew Berry': 172, 'Grepa Berry': 173, 'Tamato Berry': 174,
         'Cornn Berry': 175, 'Magost Berry': 176, 'Rabuta Berry': 177, 'Nomel Berry': 178, 'Spelon Berry': 179,
         'Pamtre Berry': 180, 'Watmel Berry': 181, 'Durin Berry': 182, 'Belue Berry': 183, 'Occa Berry': 184,
         'Passho Berry': 185, 'Wacan Berry': 186, 'Rindo Berry': 187, 'Yache Berry': 188, 'Chople Berry': 189,
         'Kebia Berry': 190, 'Shuca Berry': 191, 'Coba Berry': 192, 'Payapa Berry': 193, 'Tanga Berry': 194,
         'Charti Berry': 195, 'Kasib Berry': 196, 'Haban Berry': 197, 'Colbur Berry': 198, 'Babiri Berry': 199,
         'Chilan Berry': 200, 'Liechi Berry': 201, 'Ganlon Berry': 202, 'Salac Berry': 203, 'Petaya Berry': 204,
         'Apicot Berry': 205, 'Lansat Berry': 206, 'Starf Berry': 207, 'Enigma Berry': 208, 'Micle Berry': 209,
         'Custap Berry': 210, 'Jaboca Berry': 211, 'Rowap Berry': 212, 'Bright Powder': 213, 'White Herb': 214,
         'Macho Brace': 215, 'Exp. Share': 216, 'Quick Claw': 217, 'Soothe Bell': 218, 'Mental Herb': 219,
         'Choice Band': 220, "King's Rock": 221, 'Silver Powder': 222, 'Amulet Coin': 223, 'Cleanse Tag': 224,
         'Soul Dew': 225, 'Deep Sea Tooth': 226, 'Deep Sea Scale': 227, 'Smoke Ball': 228, 'Everstone': 229,
         'Focus Band': 230, 'Lucky Egg': 231, 'Scope Lens': 232, 'Metal Coat': 233, 'Leftovers': 234,
         'Dragon Scale': 235, 'Light Ball': 236, 'Soft Sand': 237, 'Hard Stone': 238, 'Miracle Seed': 239,
         'Black Glasses': 240, 'Black Belt': 241, 'Magnet': 242, 'Mystic Water': 243, 'Sharp Beak': 244,
         'Poison Barb': 245, 'Never-Melt Ice': 246, 'Spell Tag': 247, 'Twisted Spoon': 248, 'Charcoal': 249,
         'Dragon Fang': 250, 'Silk Scarf': 251, 'Up-Grade': 252, 'Shell Bell': 253, 'Sea Incense': 254,
         'Lax Incense': 255, 'Lucky Punch': 256, 'Metal Powder': 257, 'Thick Club': 258, 'Stick': 259, 'Red Scarf': 260,
         'Blue Scarf': 261, 'Pink Scarf': 262, 'Green Scarf': 263, 'Yellow Scarf': 264, 'Wide Lens': 265,
         'Muscle Band': 266, 'Wise Glasses': 267, 'Expert Belt': 268, 'Light Clay': 269, 'Life Orb': 270,
         'Power Herb': 271, 'Toxic Orb': 272, 'Flame Orb': 273, 'Quick Powder': 274, 'Focus Sash': 275,
         'Zoom Lens': 276, 'Metronome': 277, 'Iron Ball': 278, 'Lagging Tail': 279, 'Destiny Knot': 280,
         'Black Sludge': 281, 'Icy Rock': 282, 'Smooth Rock': 283, 'Heat Rock': 284, 'Damp Rock': 285, 'Grip Claw': 286,
         'Choice Scarf': 287, 'Sticky Barb': 288, 'Power Bracer': 289, 'Power Belt': 290, 'Power Lens': 291,
         'Power Band': 292, 'Power Anklet': 293, 'Power Weight': 294, 'Shed Shell': 295, 'Big Root': 296,
         'Choice Specs': 297, 'Flame Plate': 298, 'Splash Plate': 299, 'Zap Plate': 300, 'Meadow Plate': 301,
         'Icicle Plate': 302, 'Fist Plate': 303, 'Toxic Plate': 304, 'Earth Plate': 305, 'Sky Plate': 306,
         'Mind Plate': 307, 'Insect Plate': 308, 'Stone Plate': 309, 'Spooky Plate': 310, 'Draco Plate': 311,
         'Dread Plate': 312, 'Iron Plate': 313, 'Odd Incense': 314, 'Rock Incense': 315, 'Full Incense': 316,
         'Wave Incense': 317, 'Rose Incense': 318, 'Luck Incense': 319, 'Pure Incense': 320, 'Protector': 321,
         'Electirizer': 322, 'Magmarizer': 323, 'Dubious Disc': 324, 'Reaper Cloth': 325, 'Razor Claw': 326,
         'Razor Fang': 327, 'TM01': 328, 'TM02': 329, 'TM03': 330, 'TM04': 331, 'TM05': 332, 'TM06': 333, 'TM07': 334,
         'TM08': 335, 'TM09': 336, 'TM10': 337, 'TM11': 338, 'TM12': 339, 'TM13': 340, 'TM14': 341, 'TM15': 342,
         'TM16': 343, 'TM17': 344, 'TM18': 345, 'TM19': 346, 'TM20': 347, 'TM21': 348, 'TM22': 349, 'TM23': 350,
         'TM24': 351, 'TM25': 352, 'TM26': 353, 'TM27': 354, 'TM28': 355, 'TM29': 356, 'TM30': 357, 'TM31': 358,
         'TM32': 359, 'TM33': 360, 'TM34': 361, 'TM35': 362, 'TM36': 363, 'TM37': 364, 'TM38': 365, 'TM39': 366,
         'TM40': 367, 'TM41': 368, 'TM42': 369, 'TM43': 370, 'TM44': 371, 'TM45': 372, 'TM46': 373, 'TM47': 374,
         'TM48': 375, 'TM49': 376, 'TM50': 377, 'TM51': 378, 'TM52': 379, 'TM53': 380, 'TM54': 381, 'TM55': 382,
         'TM56': 383, 'TM57': 384, 'TM58': 385, 'TM59': 386, 'TM60': 387, 'TM61': 388, 'TM62': 389, 'TM63': 390,
         'TM64': 391, 'TM65': 392, 'TM66': 393, 'TM67': 394, 'TM68': 395, 'TM69': 396, 'TM70': 397, 'TM71': 398,
         'TM72': 399, 'TM73': 400, 'TM74': 401, 'TM75': 402, 'TM76': 403, 'TM77': 404, 'TM78': 405, 'TM79': 406,
         'TM80': 407, 'TM81': 408, 'TM82': 409, 'TM83': 410, 'TM84': 411, 'TM85': 412, 'TM86': 413, 'TM87': 414,
         'TM88': 415, 'TM89': 416, 'TM90': 417, 'TM91': 418, 'TM92': 419, 'HM01': 420, 'HM02': 421, 'HM03': 422,
         'HM04': 423, 'HM05': 424, 'HM06': 425, 'Explorer Kit': 428, 'Loot Sack': 429, 'Rule Book': 430,
         'Poké Radar': 431, 'Point Card': 432, 'Journal': 433, 'Seal Case': 434, 'Fashion Case': 435, 'Seal Bag': 436,
         'Pal Pad': 437, 'Works Key': 438, 'Old Charm': 439, 'Galactic Key': 440, 'Red Chain': 441, 'Town Map': 442,
         'Vs. Seeker': 443, 'Coin Case': 444, 'Old Rod': 445, 'Good Rod': 446, 'Super Rod': 447, 'Sprayduck': 448,
         'Poffin Case': 449, 'Bike': 450, 'Suite Key': 451, "Oak's Letter": 452, 'Lunar Wing': 453, 'Member Card': 454,
         'Azure Flute': 455, 'S.S. Ticket': 456, 'Contest Pass': 457, 'Magma Stone': 458, 'Parcel': 459,
         'Coupon 1': 460, 'Coupon 2': 461, 'Coupon 3': 462, 'Storage Key': 463, 'Secret Potion': 464,
         'Vs. Recorder': 465, 'Gracidea': 466, 'Secret Key': 467, 'Apricorn Box': 468, 'Unown Report': 469,
         'Berry Pots': 470, 'Dowsing Machine': 471, 'Blue Card': 472, 'Slowpoke Tail': 473, 'Clear Bell': 474,
         'Card Key': 475, 'Basement Key': 476, 'Squirt Bottle': 477, 'Red Scale': 478, 'Lost Item': 479, 'Pass': 480,
         'Machine Part': 481, 'Silver Wing': 482, 'Rainbow Wing': 483, 'Mystery Egg': 484, 'Red Apricorn': 485,
         'Blue Apricorn': 486, 'Yellow Apricorn': 487, 'Green Apricorn': 488, 'Pink Apricorn': 489,
         'White Apricorn': 490, 'Black Apricorn': 491, 'Fast Ball': 492, 'Level Ball': 493, 'Lure Ball': 494,
         'Heavy Ball': 495, 'Love Ball': 496, 'Friend Ball': 497, 'Moon Ball': 498, 'Sport Ball': 499, 'Park Ball': 500,
         'Photo Album': 501, 'GB Sounds': 502, 'Tidal Bell': 503, 'RageCandyBar': 504, 'Data Card 01': 505,
         'Data Card 02': 506, 'Data Card 03': 507, 'Data Card 04': 508, 'Data Card 05': 509, 'Data Card 06': 510,
         'Data Card 07': 511, 'Data Card 08': 512, 'Data Card 09': 513, 'Data Card 10': 514, 'Data Card 11': 515,
         'Data Card 12': 516, 'Data Card 13': 517, 'Data Card 14': 518, 'Data Card 15': 519, 'Data Card 16': 520,
         'Data Card 17': 521, 'Data Card 18': 522, 'Data Card 19': 523, 'Data Card 20': 524, 'Data Card 21': 525,
         'Data Card 22': 526, 'Data Card 23': 527, 'Data Card 24': 528, 'Data Card 25': 529, 'Data Card 26': 530,
         'Data Card 27': 531, 'Jade Orb': 532, 'Lock Capsule': 533, 'Red Orb': 534, 'Blue Orb': 535,
         'Enigma Stone': 536, 'Prism Scale': 537, 'Eviolite': 538, 'Float Stone': 539, 'Rocky Helmet': 540,
         'Air Balloon': 541, 'Red Card': 542, 'Ring Target': 543, 'Binding Band': 544, 'Absorb Bulb': 545,
         'Cell Battery': 546, 'Eject Button': 547, 'Fire Gem': 548, 'Water Gem': 549, 'Electric Gem': 550,
         'Grass Gem': 551, 'Ice Gem': 552, 'Fighting Gem': 553, 'Poison Gem': 554, 'Ground Gem': 555, 'Flying Gem': 556,
         'Psychic Gem': 557, 'Bug Gem': 558, 'Rock Gem': 559, 'Ghost Gem': 560, 'Dragon Gem': 561, 'Dark Gem': 562,
         'Steel Gem': 563, 'Normal Gem': 564, 'Health Wing': 565, 'Muscle Wing': 566, 'Resist Wing': 567,
         'Genius Wing': 568, 'Clever Wing': 569, 'Swift Wing': 570, 'Pretty Wing': 571, 'Cover Fossil': 572,
         'Plume Fossil': 573, 'Liberty Pass': 574, 'Pass Orb': 575, 'Dream Ball': 576, 'Poké Toy': 577,
         'Prop Case': 578, 'Dragon Skull': 579, 'Balm Mushroom': 580, 'Big Nugget': 581, 'Pearl String': 582,
         'Comet Shard': 583, 'Relic Copper': 584, 'Relic Silver': 585, 'Relic Gold': 586, 'Relic Vase': 587,
         'Relic Band': 588, 'Relic Statue': 589, 'Relic Crown': 590, 'Casteliacone': 591, 'Dire Hit 2': 592,
         'X Speed 2': 593, 'X Sp. Atk 2': 594, 'X Sp. Def 2': 595, 'X Defense 2': 596, 'X Attack 2': 597,
         'X Accuracy 2': 598, 'X Speed 3': 599, 'X Sp. Atk 3': 600, 'X Sp. Def 3': 601, 'X Defense 3': 602,
         'X Attack 3': 603, 'X Accuracy 3': 604, 'X Speed 6': 605, 'X Sp. Atk 6': 606, 'X Sp. Def 6': 607,
         'X Defense 6': 608, 'X Attack 6': 609, 'X Accuracy 6': 610, 'Ability Urge': 611, 'Item Drop': 612,
         'Item Urge': 613, 'Reset Urge': 614, 'Dire Hit 3': 615, 'Light Stone': 616, 'Dark Stone': 617, 'TM93': 618,
         'TM94': 619, 'TM95': 620, 'Xtransceiver': 626, 'God Stone': 622, 'Gram 1': 623, 'Gram 2': 624, 'Gram 3': 625,
         'Medal Box': 627, 'DNA Splicers': 629, 'Permit': 630, 'Oval Charm': 631, 'Shiny Charm': 632,
         'Plasma Card': 633, 'Grubby Hanky': 634, 'Colress Machine': 635, 'Dropped Item': 637, 'Reveal Glass': 638}
types = {1: ['Grass', 'Poison'], 2: ['Grass', 'Poison'], 3: ['Grass', 'Poison'], 4: ['Fire', ''], 5: ['Fire', ''],
         6: ['Fire', 'Flying'], 7: ['Water', ''], 8: ['Water', ''], 9: ['Water', ''], 10: ['Bug', ''],
         11: ['Bug', ''], 12: ['Bug', 'Flying'], 13: ['Bug', 'Poison'], 14: ['Bug', 'Poison'], 15: ['Bug', 'Poison'],
         16: ['Normal', 'Flying'], 17: ['Normal', 'Flying'], 18: ['Normal', 'Flying'], 19: ['Normal', ''],
         20: ['Normal', ''], 21: ['Normal', 'Flying'], 22: ['Normal', 'Flying'], 23: ['Poison', ''],
         24: ['Poison', ''], 25: ['Electric', ''], 26: ['Electric', ''], 27: ['Ground', ''], 28: ['Ground', ''],
         29: ['Poison', ''], 30: ['Poison', ''], 31: ['Poison', 'Ground'], 32: ['Poison', ''], 33: ['Poison', ''],
         34: ['Poison', 'Ground'], 35: ['Normal', ''], 36: ['Normal', ''], 37: ['Fire', ''], 38: ['Fire', ''],
         39: ['Normal', ''], 40: ['Normal', ''], 41: ['Poison', 'Flying'], 42: ['Poison', 'Flying'],
         43: ['Grass', 'Poison'], 44: ['Grass', 'Poison'], 45: ['Grass', 'Poison'], 46: ['Bug', 'Grass'],
         47: ['Bug', 'Grass'], 48: ['Bug', 'Poison'], 49: ['Bug', 'Poison'], 50: ['Ground', ''], 51: ['Ground', ''],
         52: ['Normal', ''], 53: ['Normal', ''], 54: ['Water', ''], 55: ['Water', ''], 56: ['Fighting', ''],
         57: ['Fighting', ''], 58: ['Fire', ''], 59: ['Fire', ''], 60: ['Water', ''], 61: ['Water', ''],
         62: ['Water', 'Fighting'], 63: ['Psychic', ''], 64: ['Psychic', ''], 65: ['Psychic', ''],
         66: ['Fighting', ''], 67: ['Fighting', ''], 68: ['Fighting', ''], 69: ['Grass', 'Poison'],
         70: ['Grass', 'Poison'], 71: ['Grass', 'Poison'], 72: ['Water', 'Poison'], 73: ['Water', 'Poison'],
         74: ['Rock', 'Ground'], 75: ['Rock', 'Ground'], 76: ['Rock', 'Ground'], 77: ['Fire', ''], 78: ['Fire', ''],
         79: ['Water', 'Psychic'], 80: ['Water', 'Psychic'], 81: ['Electric', 'Steel'], 82: ['Electric', 'Steel'],
         83: ['Normal', 'Flying'], 84: ['Normal', 'Flying'], 85: ['Normal', 'Flying'], 86: ['Water', ''],
         87: ['Water', 'Ice'], 88: ['Poison', ''], 89: ['Poison', ''], 90: ['Water', ''], 91: ['Water', 'Ice'],
         92: ['Ghost', 'Poison'], 93: ['Ghost', 'Poison'], 94: ['Ghost', 'Poison'], 95: ['Rock', 'Ground'],
         96: ['Psychic', ''], 97: ['Psychic', ''], 98: ['Water', ''], 99: ['Water', ''], 100: ['Electric', ''],
         101: ['Electric', ''], 102: ['Grass', 'Psychic'], 103: ['Grass', 'Psychic'], 104: ['Ground', ''],
         105: ['Ground', ''], 106: ['Fighting', ''], 107: ['Fighting', ''], 108: ['Normal', ''],
         109: ['Poison', ''], 110: ['Poison', ''], 111: ['Ground', 'Rock'], 112: ['Ground', 'Rock'],
         113: ['Normal', ''], 114: ['Grass', ''], 115: ['Normal', ''], 116: ['Water', ''], 117: ['Water', ''],
         118: ['Water', ''], 119: ['Water', ''], 120: ['Water', ''], 121: ['Water', 'Psychic'],
         122: ['Psychic', ''], 123: ['Bug', 'Flying'], 124: ['Ice', 'Psychic'], 125: ['Electric', ''],
         126: ['Fire', ''], 127: ['Bug', ''], 128: ['Normal', ''], 129: ['Water', ''], 130: ['Water', 'Flying'],
         131: ['Water', 'Ice'], 132: ['Normal', ''], 133: ['Normal', ''], 134: ['Water', ''], 135: ['Electric', ''],
         136: ['Fire', ''], 137: ['Normal', ''], 138: ['Rock', 'Water'], 139: ['Rock', 'Water'],
         140: ['Rock', 'Water'], 141: ['Rock', 'Water'], 142: ['Rock', 'Flying'], 143: ['Normal', ''],
         144: ['Ice', 'Flying'], 145: ['Electric', 'Flying'], 146: ['Fire', 'Flying'], 147: ['Dragon', ''],
         148: ['Dragon', ''], 149: ['Dragon', 'Flying'], 150: ['Psychic', ''], 151: ['Psychic', ''],
         152: ['Grass', ''], 153: ['Grass', ''], 154: ['Grass', ''], 155: ['Fire', ''], 156: ['Fire', ''],
         157: ['Fire', ''], 158: ['Water', ''], 159: ['Water', ''], 160: ['Water', ''], 161: ['Normal', ''],
         162: ['Normal', ''], 163: ['Normal', 'Flying'], 164: ['Normal', 'Flying'], 165: ['Bug', 'Flying'],
         166: ['Bug', 'Flying'], 167: ['Bug', 'Poison'], 168: ['Bug', 'Poison'], 169: ['Poison', 'Flying'],
         170: ['Water', 'Electric'], 171: ['Water', 'Electric'], 172: ['Electric', ''], 173: ['Normal', ''],
         174: ['Normal', ''], 175: ['Normal', ''], 176: ['Normal', 'Flying'], 177: ['Psychic', 'Flying'],
         178: ['Psychic', 'Flying'], 179: ['Electric', ''], 180: ['Electric', ''], 181: ['Electric', ''],
         182: ['Grass', ''], 183: ['Water', ''], 184: ['Water', ''], 185: ['Rock', ''], 186: ['Water', ''],
         187: ['Grass', 'Flying'], 188: ['Grass', 'Flying'], 189: ['Grass', 'Flying'], 190: ['Normal', ''],
         191: ['Grass', ''], 192: ['Grass', ''], 193: ['Bug', 'Flying'], 194: ['Water', 'Ground'],
         195: ['Water', 'Ground'], 196: ['Psychic', ''], 197: ['Dark', ''], 198: ['Dark', 'Flying'],
         199: ['Water', 'Psychic'], 200: ['Ghost', ''], 201: ['Psychic', ''], 202: ['Psychic', ''],
         203: ['Normal', 'Psychic'], 204: ['Bug', ''], 205: ['Bug', 'Steel'], 206: ['Normal', ''],
         207: ['Ground', 'Flying'], 208: ['Steel', 'Ground'], 209: ['Normal', ''], 210: ['Normal', ''],
         211: ['Water', 'Poison'], 212: ['Bug', 'Steel'], 213: ['Bug', 'Rock'], 214: ['Bug', 'Fighting'],
         215: ['Dark', 'Ice'], 216: ['Normal', ''], 217: ['Normal', ''], 218: ['Fire', ''], 219: ['Fire', 'Rock'],
         220: ['Ice', 'Ground'], 221: ['Ice', 'Ground'], 222: ['Water', 'Rock'], 223: ['Water', ''],
         224: ['Water', ''], 225: ['Ice', 'Flying'], 226: ['Water', 'Flying'], 227: ['Steel', 'Flying'],
         228: ['Dark', 'Fire'], 229: ['Dark', 'Fire'], 230: ['Water', 'Dragon'], 231: ['Ground', ''],
         232: ['Ground', ''], 233: ['Normal', ''], 234: ['Normal', ''], 235: ['Normal', ''], 236: ['Fighting', ''],
         237: ['Fighting', ''], 238: ['Ice', 'Psychic'], 239: ['Electric', ''], 240: ['Fire', ''],
         241: ['Normal', ''], 242: ['Normal', ''], 243: ['Electric', ''], 244: ['Fire', ''], 245: ['Water', ''],
         246: ['Rock', 'Ground'], 247: ['Rock', 'Ground'], 248: ['Rock', 'Dark'], 249: ['Psychic', 'Flying'],
         250: ['Fire', 'Flying'], 251: ['Psychic', 'Grass'], 252: ['Grass', ''], 253: ['Grass', ''],
         254: ['Grass', ''], 255: ['Fire', ''], 256: ['Fire', 'Fighting'], 257: ['Fire', 'Fighting'],
         258: ['Water', ''], 259: ['Water', 'Ground'], 260: ['Water', 'Ground'], 261: ['Dark', ''],
         262: ['Dark', ''], 263: ['Normal', ''], 264: ['Normal', ''], 265: ['Bug', ''], 266: ['Bug', ''],
         267: ['Bug', 'Flying'], 268: ['Bug', ''], 269: ['Bug', 'Poison'], 270: ['Water', 'Grass'],
         271: ['Water', 'Grass'], 272: ['Water', 'Grass'], 273: ['Grass', ''], 274: ['Grass', 'Dark'],
         275: ['Grass', 'Dark'], 276: ['Normal', 'Flying'], 277: ['Normal', 'Flying'], 278: ['Water', 'Flying'],
         279: ['Water', 'Flying'], 280: ['Psychic', ''], 281: ['Psychic', ''], 282: ['Psychic', ''],
         283: ['Bug', 'Water'], 284: ['Bug', 'Flying'], 285: ['Grass', ''], 286: ['Grass', 'Fighting'],
         287: ['Normal', ''], 288: ['Normal', ''], 289: ['Normal', ''], 290: ['Bug', 'Ground'],
         291: ['Bug', 'Flying'], 292: ['Bug', 'Ghost'], 293: ['Normal', ''], 294: ['Normal', ''],
         295: ['Normal', ''], 296: ['Fighting', ''], 297: ['Fighting', ''], 298: ['Normal', ''],
         299: ['Rock', ''], 300: ['Normal', ''], 301: ['Normal', ''], 302: ['Dark', 'Ghost'],
         303: ['Steel', ''], 304: ['Steel', 'Rock'], 305: ['Steel', 'Rock'], 306: ['Steel', 'Rock'],
         307: ['Fighting', 'Psychic'], 308: ['Fighting', 'Psychic'], 309: ['Electric', ''], 310: ['Electric', ''],
         311: ['Electric', ''], 312: ['Electric', ''], 313: ['Bug', ''], 314: ['Bug', ''], 315: ['Grass', 'Poison'],
         316: ['Poison', ''], 317: ['Poison', ''], 318: ['Water', 'Dark'], 319: ['Water', 'Dark'],
         320: ['Water', ''], 321: ['Water', ''], 322: ['Fire', 'Ground'], 323: ['Fire', 'Ground'], 324: ['Fire', ''],
         325: ['Psychic', ''], 326: ['Psychic', ''], 327: ['Normal', ''], 328: ['Ground', ''],
         329: ['Ground', 'Dragon'], 330: ['Ground', 'Dragon'], 331: ['Grass', ''], 332: ['Grass', 'Dark'],
         333: ['Normal', 'Flying'], 334: ['Dragon', 'Flying'], 335: ['Normal', ''], 336: ['Poison', ''],
         337: ['Rock', 'Psychic'], 338: ['Rock', 'Psychic'], 339: ['Water', 'Ground'], 340: ['Water', 'Ground'],
         341: ['Water', ''], 342: ['Water', 'Dark'], 343: ['Ground', 'Psychic'], 344: ['Ground', 'Psychic'],
         345: ['Rock', 'Grass'], 346: ['Rock', 'Grass'], 347: ['Rock', 'Bug'], 348: ['Rock', 'Bug'],
         349: ['Water', ''], 350: ['Water', ''], 351: ['Normal', ''], 352: ['Normal', ''], 353: ['Ghost', ''],
         354: ['Ghost', ''], 355: ['Ghost', ''], 356: ['Ghost', ''], 357: ['Grass', 'Flying'], 358: ['Psychic', ''],
         359: ['Dark', ''], 360: ['Psychic', ''], 361: ['Ice', ''], 362: ['Ice', ''], 363: ['Ice', 'Water'],
         364: ['Ice', 'Water'], 365: ['Ice', 'Water'], 366: ['Water', ''], 367: ['Water', ''], 368: ['Water', ''],
         369: ['Water', 'Rock'], 370: ['Water', ''], 371: ['Dragon', ''], 372: ['Dragon', ''],
         373: ['Dragon', 'Flying'], 374: ['Steel', 'Psychic'], 375: ['Steel', 'Psychic'], 376: ['Steel', 'Psychic'],
         377: ['Rock', ''], 378: ['Ice', ''], 379: ['Steel', ''], 380: ['Dragon', 'Psychic'],
         381: ['Dragon', 'Psychic'], 382: ['Water', ''], 383: ['Ground', ''], 384: ['Dragon', 'Flying'],
         385: ['Steel', 'Psychic'], 386: ['Psychic', ''], 387: ['Grass', ''], 388: ['Grass', ''],
         389: ['Grass', 'Ground'], 390: ['Fire', ''], 391: ['Fire', 'Fighting'], 392: ['Fire', 'Fighting'],
         393: ['Water', ''], 394: ['Water', ''], 395: ['Water', 'Steel'], 396: ['Normal', 'Flying'],
         397: ['Normal', 'Flying'], 398: ['Normal', 'Flying'], 399: ['Normal', ''], 400: ['Normal', 'Water'],
         401: ['Bug', ''], 402: ['Bug', ''], 403: ['Electric', ''], 404: ['Electric', ''], 405: ['Electric', ''],
         406: ['Grass', 'Poison'], 407: ['Grass', 'Poison'], 408: ['Rock', ''], 409: ['Rock', ''],
         410: ['Rock', 'Steel'], 411: ['Rock', 'Steel'], 412: ['Bug', ''], 413: ['Bug', 'Grass'],
         414: ['Bug', 'Flying'], 415: ['Bug', 'Flying'], 416: ['Bug', 'Flying'], 417: ['Electric', ''],
         418: ['Water', ''], 419: ['Water', ''], 420: ['Grass', ''], 421: ['Grass', ''], 422: ['Water', ''],
         423: ['Water', 'Ground'], 424: ['Normal', ''], 425: ['Ghost', 'Flying'], 426: ['Ghost', 'Flying'],
         427: ['Normal', ''], 428: ['Normal', ''], 429: ['Ghost', ''], 430: ['Dark', 'Flying'], 431: ['Normal', ''],
         432: ['Normal', ''], 433: ['Psychic', ''], 434: ['Poison', 'Dark'], 435: ['Poison', 'Dark'],
         436: ['Steel', 'Psychic'], 437: ['Steel', 'Psychic'], 438: ['Rock', ''], 439: ['Psychic', ''],
         440: ['Normal', ''], 441: ['Normal', 'Flying'], 442: ['Ghost', 'Dark'], 443: ['Dragon', 'Ground'],
         444: ['Dragon', 'Ground'], 445: ['Dragon', 'Ground'], 446: ['Normal', ''], 447: ['Fighting', ''],
         448: ['Fighting', 'Steel'], 449: ['Ground', ''], 450: ['Ground', ''], 451: ['Poison', 'Bug'],
         452: ['Poison', 'Dark'], 453: ['Poison', 'Fighting'], 454: ['Poison', 'Fighting'], 455: ['Grass', ''],
         456: ['Water', ''], 457: ['Water', ''], 458: ['Water', 'Flying'], 459: ['Grass', 'Ice'],
         460: ['Grass', 'Ice'], 461: ['Dark', 'Ice'], 462: ['Electric', 'Steel'], 463: ['Normal', ''],
         464: ['Ground', 'Rock'], 465: ['Grass', ''], 466: ['Electric', ''], 467: ['Fire', ''],
         468: ['Normal', 'Flying'], 469: ['Bug', 'Flying'], 470: ['Grass', ''], 471: ['Ice', ''],
         472: ['Ground', 'Flying'], 473: ['Ice', 'Ground'], 474: ['Normal', ''], 475: ['Psychic', 'Fighting'],
         476: ['Rock', 'Steel'], 477: ['Ghost', ''], 478: ['Ice', 'Ghost'], 479: ['Electric', 'Ghost'],
         480: ['Psychic', ''], 481: ['Psychic', ''], 482: ['Psychic', ''], 483: ['Steel', 'Dragon'],
         484: ['Water', 'Dragon'], 485: ['Fire', 'Steel'], 486: ['Normal', ''], 487: ['Ghost', 'Dragon'],
         488: ['Psychic', ''], 489: ['Water', ''], 490: ['Water', ''], 491: ['Dark', ''], 492: ['Grass', ''],
         493: ['Normal', ''], 494: ['Psychic', 'Fire'], 495: ['Grass', ''], 496: ['Grass', ''], 497: ['Grass', ''],
         498: ['Fire', ''], 499: ['Fire', 'Fighting'], 500: ['Fire', 'Fighting'], 501: ['Water', ''],
         502: ['Water', ''], 503: ['Water', ''], 504: ['Normal', ''], 505: ['Normal', ''], 506: ['Normal', ''],
         507: ['Normal', ''], 508: ['Normal', ''], 509: ['Dark', ''], 510: ['Dark', ''], 511: ['Grass', ''],
         512: ['Grass', ''], 513: ['Fire', ''], 514: ['Fire', ''], 515: ['Water', ''], 516: ['Water', ''],
         517: ['Psychic', ''], 518: ['Psychic', ''], 519: ['Normal', 'Flying'], 520: ['Normal', 'Flying'],
         521: ['Normal', 'Flying'], 522: ['Electric', ''], 523: ['Electric', ''], 524: ['Rock', ''],
         525: ['Rock', ''], 526: ['Rock', ''], 527: ['Psychic', 'Flying'], 528: ['Psychic', 'Flying'],
         529: ['Ground', ''], 530: ['Ground', 'Steel'], 531: ['Normal', ''], 532: ['Fighting', ''],
         533: ['Fighting', ''], 534: ['Fighting', ''], 535: ['Water', ''], 536: ['Water', 'Ground'],
         537: ['Water', 'Ground'], 538: ['Fighting', ''], 539: ['Fighting', ''], 540: ['Bug', 'Grass'],
         541: ['Bug', 'Grass'], 542: ['Bug', 'Grass'], 543: ['Bug', 'Poison'], 544: ['Bug', 'Poison'],
         545: ['Bug', 'Poison'], 546: ['Grass', ''], 547: ['Grass', ''], 548: ['Grass', ''],
         549: ['Grass', ''], 550: ['Water', ''], 551: ['Ground', 'Dark'], 552: ['Ground', 'Dark'],
         553: ['Ground', 'Dark'], 554: ['Fire', ''], 555: ['Fire', ''], 556: ['Grass', ''], 557: ['Bug', 'Rock'],
         558: ['Bug', 'Rock'], 559: ['Dark', 'Fighting'], 560: ['Dark', 'Fighting'], 561: ['Psychic', 'Flying'],
         562: ['Ghost', ''], 563: ['Ghost', ''], 564: ['Water', 'Rock'], 565: ['Water', 'Rock'],
         566: ['Rock', 'Flying'], 567: ['Rock', 'Flying'], 568: ['Poison', ''], 569: ['Poison', ''],
         570: ['Dark', ''], 571: ['Dark', ''], 572: ['Normal', ''], 573: ['Normal', ''], 574: ['Psychic', ''],
         575: ['Psychic', ''], 576: ['Psychic', ''], 577: ['Psychic', ''], 578: ['Psychic', ''],
         579: ['Psychic', ''], 580: ['Water', 'Flying'], 581: ['Water', 'Flying'], 582: ['Ice', ''],
         583: ['Ice', ''], 584: ['Ice', ''], 585: ['Normal', 'Grass'], 586: ['Normal', 'Grass'],
         587: ['Electric', 'Flying'], 588: ['Bug', ''], 589: ['Bug', 'Steel'], 590: ['Grass', 'Poison'],
         591: ['Grass', 'Poison'], 592: ['Water', 'Ghost'], 593: ['Water', 'Ghost'], 594: ['Water', ''],
         595: ['Bug', 'Electric'], 596: ['Bug', 'Electric'], 597: ['Grass', 'Steel'], 598: ['Grass', 'Steel'],
         599: ['Steel', ''], 600: ['Steel', ''], 601: ['Steel', ''], 602: ['Electric', ''], 603: ['Electric', ''],
         604: ['Electric', ''], 605: ['Psychic', ''], 606: ['Psychic', ''], 607: ['Ghost', 'Fire'],
         608: ['Ghost', 'Fire'], 609: ['Ghost', 'Fire'], 610: ['Dragon', ''], 611: ['Dragon', ''],
         612: ['Dragon', ''], 613: ['Ice', ''], 614: ['Ice', ''], 615: ['Ice', ''], 616: ['Bug', ''],
         617: ['Bug', ''], 618: ['Ground', 'Electric'], 619: ['Fighting', ''], 620: ['Fighting', ''],
         621: ['Dragon', ''], 622: ['Ground', 'Ghost'], 623: ['Ground', 'Ghost'], 624: ['Dark', 'Steel'],
         625: ['Dark', 'Steel'], 626: ['Normal', ''], 627: ['Normal', 'Flying'], 628: ['Normal', 'Flying'],
         629: ['Dark', 'Flying'], 630: ['Dark', 'Flying'], 631: ['Fire', ''], 632: ['Bug', 'Steel'],
         633: ['Dark', 'Dragon'], 634: ['Dark', 'Dragon'], 635: ['Dark', 'Dragon'], 636: ['Bug', 'Fire'],
         637: ['Bug', 'Fire'], 638: ['Steel', 'Fighting'], 639: ['Rock', 'Fighting'], 640: ['Grass', 'Fighting'],
         641: ['Flying', ''], 642: ['Electric', 'Flying'], 643: ['Dragon', 'Fire'], 644: ['Dragon', 'Electric'],
         645: ['Ground', 'Flying'], 646: ['Dragon', 'Ice'], 647: ['Water', 'Fighting'], 648: ['Normal', 'Psychic'],
         649: ['Bug', 'Steel']}

formtypes = {413: [['Bug', 'Grass'], ['Bug', 'Ground'], ['Bug', 'Steel']],
             479: [['Electric', 'Ghost'], ['Electric', 'Fire'], ['Electric', 'Water'],
                   ['Electric', 'Ice'], ['Electric', 'Flying'], ['Electric', 'Grass']],
             492: [['Grass'], ['Grass', 'Flying']],
             493: [["Normal"], ["Fighting"], ["Flying"], ["Poison"], ["Ground"], ["Rock"], ["Bug"], ["Ghost"],
                   ["Steel"], ["Fire"], ["Water"], ["Grass"], ["Electric"], ["Psychic"], ["Ice"], ["Dragon"], ["Dark"]],
             648: [['Normal', 'Psychic'], ['Normal', 'Fighting']]}

# d = {}
# for i in types.split('\n')[1:]:
#     if int(i.split(',')[0]) not in d:
#         d[int(i.split(',')[0])] = [i.split(',')[3].strip('"'), i.split(',')[4].strip('"')]
# print(d)

# p = {}
# for i in moves:
#     p[i['id']] = {'name': i['name'], 'gender': (i['gender'].capitalize() if i['gender'] != 'unknown' else
#     'GENDERLESS')
#     if 'gender' in i else 'GENDERLESS', 'forms': i['forms'] if 'forms' in i else '0'}
# print(p)
# for i in pkms:
#     pkms[i]['forms'] = [o for o in range(len(pkms[i]['forms']))]
# print(pkms)

# p = {}
# for i in items:
#     p[i['name']] = i['id']
# print(p)
