name: EntralinkedRandomizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: ./ # or path/to/artifact

    - uses: actions/download-artifact@v2.1.1
      with:
        name: my-exe
        path: ./ # or path/to/artifact
